<script setup lang="ts">
// Layer-1 pure-UI component generated by Forge (component_StatCard).
defineProps<{
  label: string
  value: string | number
}>()
</script>

<template>
  <div class="stat-card rounded-xl border p-4">
    <div class="text-sm text-muted-foreground">{{ label }}</div>
    <div class="mt-1 text-2xl font-semibold tabular-nums">{{ value }}</div>
  </div>
</template>
