import { afterEach, expect, it, vi } from 'vitest';
afterEach(() => vi.unstubAllGlobals());
import { mount, flushSync, unmount } from 'svelte';
import UiHarness from './UiHarness.svelte';

it('persists sidebar preferences, bounds panel sizes, and handles menu/chat state', async () => {
  vi.stubGlobal('matchMedia', (query: string) => ({ matches: true, media: query, addEventListener() {}, removeEventListener() {} }));
  const target = document.createElement('div');
  document.body.append(target);
  const component = mount(UiHarness, { target });
  const store = component.store;
  flushSync();
  expect(target.textContent).toContain(store.breakpoint);
  expect([store.isMobile, store.isMedium, store.isDesktop].filter(Boolean)).toHaveLength(1);
  store.setSidebarCollapsed(false);
  store.toggleSidebar();
  expect(store.sidebarCollapsed).toBe(true);
  expect(localStorage.getItem('sidebar-collapsed')).toBe('true');
  store.toggleMobileMenu();
  expect(store.mobileMenuOpen).toBe(true);
  store.closeMobileMenu();
  expect(store.mobileMenuOpen).toBe(false);
  store.openChat();
  expect(store.chatOpen).toBe(true);
  store.toggleChat();
  expect(store.chatOpen).toBe(false);
  store.openChat();
  store.closeChat();
  expect(store.chatOpen).toBe(false);
  store.setChatWidth(100000);
  const maximum = store.chatWidth;
  expect(maximum).toBeLessThan(100000);
  store.setChatWidth(-1);
  expect(store.chatWidth).toBeGreaterThan(0);
  expect(store.chatWidth).toBeLessThan(maximum);
  expect(localStorage.getItem('chat-width')).toBe(String(store.chatWidth));
  store.setChatWidthRatio(0.9);
  expect(store.chatWidthRatio).toBe(0.5);
  store.setChatWidthRatio(-1);
  expect(store.chatWidthRatio).toBe(0.2);
  expect(localStorage.getItem('chat-width-ratio')).toBe('0.2');
  await unmount(component);
  target.remove();
});
