"""`forge --component-cmd ...` / `--template-cmd ...` — layered-component verbs.

Subcommands:

* ``--component-cmd list``      — enumerate registered components (all layers).
* ``--component-cmd scaffold``  — render a layer-aware component skeleton.
* ``--template-cmd list``       — enumerate Layer-3 templates (layer == 3).

Component *selection* into a project is config-driven (``components: [...]``);
these verbs are for discovery + authoring, mirroring ``--features-cmd``.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import cast

from forge import telemetry

_PASCAL = re.compile(r"^[A-Z][A-Za-z0-9]*$")


def _ensure_loaded() -> None:
    """Populate COMPONENT_REGISTRY from built-in features if not already."""
    from forge.feature_loader import load_builtin_features  # noqa: PLC0415

    load_builtin_features()


def _component_rows(*, layer: int | None = None) -> list[dict[str, object]]:
    from forge.components import COMPONENT_REGISTRY  # noqa: PLC0415

    rows: list[dict[str, object]] = []
    for node in sorted(COMPONENT_REGISTRY.values(), key=lambda n: n.name):
        if layer is not None and node.layer != layer:
            continue
        rows.append(
            {
                "name": node.name,
                "layer": node.layer,
                "version": node.version,
                "contract": node.contract,
                "children": sorted(node.children),
            }
        )
    return rows


def _print_rows(rows: list[dict[str, object]], *, json_output: bool, empty_msg: str) -> None:
    if json_output:
        print(json.dumps(rows, indent=2))
        return
    if not rows:
        print(empty_msg)
        return
    width = max(len(str(r["name"])) for r in rows)
    for r in rows:
        child_names = cast("list[str]", r["children"])
        children = f"  children: {', '.join(child_names)}" if child_names else ""
        contract = f"  contract: {r['contract']}" if r["contract"] else ""
        print(f"  L{r['layer']}  {str(r['name']):<{width}}  {r['version']}{contract}{children}")


def _dispatch_components(
    subcommand: str,
    *,
    json_output: bool = False,
    name: str | None = None,
    layer: int = 1,
) -> None:
    """Dispatch a ``--component-cmd`` subcommand and exit."""
    if subcommand == "list":
        _ensure_loaded()
        _print_rows(_component_rows(), json_output=json_output, empty_msg="No components.")
        telemetry.emit(telemetry.EVENT_COMPONENT_RAN, action="list")
        sys.exit(0)

    if subcommand == "scaffold":
        if not name:
            print(
                "scaffold requires a name: "
                "`forge --component-cmd scaffold --component-name <PascalName>`",
                file=sys.stderr,
            )
            sys.exit(2)
        _scaffold_component(name, layer=layer)
        telemetry.emit(telemetry.EVENT_COMPONENT_RAN, action="scaffold")
        sys.exit(0)

    print(f"Unknown component subcommand: {subcommand!r}", file=sys.stderr)
    sys.exit(2)


def _dispatch_templates(
    subcommand: str, *, json_output: bool = False, name: str | None = None
) -> None:
    """Dispatch a ``--template-cmd`` subcommand and exit."""
    if subcommand == "list":
        _ensure_loaded()
        _print_rows(_component_rows(layer=3), json_output=json_output, empty_msg="No templates.")
        telemetry.emit(telemetry.EVENT_TEMPLATE_RAN, action="list")
        sys.exit(0)

    print(f"Unknown template subcommand: {subcommand!r}", file=sys.stderr)
    sys.exit(2)


# ---------------------------------------------------------------------------
# scaffold
# ---------------------------------------------------------------------------

# Token-replacement stubs (NOT str.format — the Vue/TS/JSON bodies are
# brace-heavy). Placeholders: __NAME__ / __LAYER__ / __SNAKE__.
_VUE_STUB = """\
<script setup lang="ts">
// Layer-__LAYER__ component generated by Forge (component___NAME__).
defineProps<{
  label: string
}>()
</script>

<template>
  <div class="__SNAKE__">{{ label }}</div>
</template>
"""

_FEATURE_TOML = """\
[feature]
name = "__NAME__"
version = "0.1.0"
summary = "__NAME__ — Layer-__LAYER__ component (scaffolded)."
category = "component"
stability = "experimental"
layer = __LAYER__
"""

_INIT_PY = '''\
"""__NAME__ — a Layer-__LAYER__ component. The loader auto-registers its emitter
fragment from this manifest; no options/fragments of its own."""

from __future__ import annotations

from forge.api import ForgeAPI


def register(api: ForgeAPI) -> None:  # noqa: ARG001
    return None
'''

_PROPS_STUB = """\
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "__NAME__Props",
  "type": "object",
  "properties": { "label": { "type": "string" } },
  "required": ["label"],
  "additionalProperties": false
}
"""


def _render(stub: str, *, name: str, layer: int, snake: str) -> str:
    return (
        stub.replace("__NAME__", name).replace("__LAYER__", str(layer)).replace("__SNAKE__", snake)
    )


def _snake(name: str) -> str:
    s = re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()
    return re.sub(r"[^a-z0-9_]", "_", s)


def _scaffold_component(name: str, *, layer: int = 1, root: Path | None = None) -> None:
    """Render a layer-aware component skeleton under ``root`` (default features dir)."""
    if not _PASCAL.match(name):
        print(f"Component name must be PascalCase (got {name!r}).", file=sys.stderr)
        sys.exit(2)
    if layer not in (1, 2, 3):
        print(f"layer must be 1, 2, or 3 (got {layer}).", file=sys.stderr)
        sys.exit(2)
    if root is None:
        root = Path(__file__).resolve().parents[2] / "features"

    snake = _snake(name)
    feat = root / snake
    if feat.exists():
        print(f"Refusing to overwrite existing directory: {feat}", file=sys.stderr)
        sys.exit(1)

    emitter = (
        feat / "templates" / f"component_{name}" / "all" / "files" / "src" / "shared" / "components"
    )
    emitter.mkdir(parents=True)
    (feat / "feature.toml").write_text(_render(_FEATURE_TOML, name=name, layer=layer, snake=snake))
    (feat / "__init__.py").write_text(_render(_INIT_PY, name=name, layer=layer, snake=snake))
    (feat / f"{name}.props.schema.json").write_text(
        _render(_PROPS_STUB, name=name, layer=layer, snake=snake)
    )
    (emitter / f"{name}.vue").write_text(_render(_VUE_STUB, name=name, layer=layer, snake=snake))

    print(f"Scaffolded Layer-{layer} component {name!r} at {feat}")
    for p in sorted(feat.rglob("*")):
        if p.is_file():
            print(f"  + {p.relative_to(root)}")
