"""`forge --plugins ...` — plugin management subcommands.

Subcommands:

* ``list`` — enumerate loaded and failed plugins discovered via the
  ``forge.plugins`` entry-point group.
* ``scaffold-fragment <name>`` — render a skeleton fragment tree
  (manifest + per-backend files + ``fragments.py`` registration stub)
  for plugin authors. Generated by Jinja2 templates that live next to
  this module under ``forge/cli/scaffold/fragment_skeleton/``.
"""

from __future__ import annotations

import json
import keyword
import shutil
import sys
from collections.abc import Sequence
from importlib import metadata as _metadata, resources
from pathlib import Path
from typing import Any

# Built-in backends the scaffold renders implementations for by default.
# Kept as a tuple of strings (not BackendLanguage members) so the CLI
# can validate ``--backends`` without coupling parser-level imports to
# the live registry — the scaffold only needs the lowercase short name
# for directory layout + the upper-case constant for the rendered
# ``BackendLanguage.<X>`` references.
_DEFAULT_BACKENDS: tuple[str, ...] = ("python", "node", "rust")
_BACKEND_CONST: dict[str, str] = {
    "python": "PYTHON",
    "node": "NODE",
    "rust": "RUST",
}


def _dispatch_plugins(
    subcommand: str,
    *,
    json_output: bool = False,
    name: str | None = None,
    output_dir: str | None = None,
    backends: str | None = None,
    force: bool = False,
) -> None:
    """Dispatch a plugins subcommand and exit."""
    from forge import plugins  # noqa: PLC0415

    # ``list`` needs the entry-point registry populated; ``scaffold-fragment``
    # is pure file IO and doesn't. Keep the load_all() call inside the
    # branch that actually reads from it.
    if subcommand == "list":
        plugins.load_all()
        _list_plugins(json_output=json_output)
        sys.exit(0)

    if subcommand == "audit":
        plugins.load_all()
        _audit_plugins(json_output=json_output)
        sys.exit(0)

    if subcommand == "scaffold-fragment":
        if not name:
            print(
                "scaffold-fragment requires a fragment name: "
                "`forge --plugins scaffold-fragment --name <NAME>`",
                file=sys.stderr,
            )
            sys.exit(2)
        backend_list = _parse_backends(backends)
        _scaffold_fragment(
            name=name,
            output_dir=output_dir,
            backends=backend_list,
            force=force,
        )
        sys.exit(0)

    print(f"Unknown plugins subcommand: {subcommand}", file=sys.stderr)
    sys.exit(1)


def _list_plugins(*, json_output: bool = False) -> None:
    from forge import plugins  # noqa: PLC0415

    if json_output:
        payload = {
            "loaded": [reg.as_dict() for reg in plugins.LOADED_PLUGINS],
            "failed": [{"name": n, "error": e} for n, e in plugins.FAILED_PLUGINS],
        }
        sys.stdout.write(json.dumps(payload, indent=2) + "\n")
        return

    loaded = plugins.LOADED_PLUGINS
    failed = plugins.FAILED_PLUGINS

    if not loaded and not failed:
        print("No forge plugins installed.")
        print("Install one with: pip install forge-plugin-<name>")
        print("See: docs/plugin-development.md")
        return

    if loaded:
        print(f"Loaded plugins ({len(loaded)}):")
        for reg in loaded:
            ver = f" v{reg.version}" if reg.version else ""
            print(f"  * {reg.name}{ver}  ({reg.module})")
            parts = []
            if reg.options_added:
                parts.append(f"{reg.options_added} option(s)")
            if reg.fragments_added:
                parts.append(f"{reg.fragments_added} fragment(s)")
            if reg.backends_added:
                parts.append(f"{reg.backends_added} backend(s)")
            if reg.commands_added:
                parts.append(f"{reg.commands_added} command(s)")
            if reg.emitters_added:
                parts.append(f"{reg.emitters_added} emitter(s)")
            if reg.extractors_added:
                parts.append(f"{len(reg.extractors_added)} extractor(s)")
            if parts:
                print(f"      adds: {', '.join(parts)}")

    if failed:
        print()
        print(f"Failed plugins ({len(failed)}):")
        for name, err in failed:
            print(f"  ! {name}: {err}")


def _audit_plugins(*, json_output: bool = False) -> None:
    """Show installed plugins with versions, source, and registration counts."""
    from forge.plugins import ENTRY_POINT_GROUP  # noqa: PLC0415

    rows: list[dict[str, Any]] = []
    eps = _metadata.entry_points()
    entry_points = (
        eps.select(group=ENTRY_POINT_GROUP) if hasattr(eps, "select") else eps.get(ENTRY_POINT_GROUP, ())
    )

    for ep in entry_points:
        dist = getattr(ep, "dist", None)
        name = ep.name
        version = str(dist.version) if dist and hasattr(dist, "version") else "unknown"
        module = getattr(ep, "value", None) or getattr(ep, "module", "<unknown>")
        source = _detect_install_source(dist)

        # Find matching loaded registration for registration counts.
        from forge import plugins  # noqa: PLC0415

        reg = next((r for r in plugins.LOADED_PLUGINS if r.name == name), None)
        registrations: dict[str, int] = {}
        if reg is not None:
            if reg.options_added:
                registrations["options"] = reg.options_added
            if reg.fragments_added:
                registrations["fragments"] = reg.fragments_added
            if reg.backends_added:
                registrations["backends"] = reg.backends_added
            if reg.commands_added:
                registrations["commands"] = reg.commands_added
            if reg.emitters_added:
                registrations["emitters"] = reg.emitters_added
            if reg.extractors_added:
                registrations["extractors"] = len(reg.extractors_added)

        # Check if this plugin failed to load.
        failed_reason = next(
            (reason for n, reason in plugins.FAILED_PLUGINS if n == name), None
        )

        rows.append({
            "name": name,
            "version": version,
            "source": source,
            "module": module,
            "status": "failed" if failed_reason else "loaded",
            "error": failed_reason,
            "registrations": registrations,
        })

    if json_output:
        sys.stdout.write(json.dumps(rows, indent=2) + "\n")
        return

    if not rows:
        print("No forge plugins installed.")
        print("Install one with: pip install forge-plugin-<name>")
        return

    # Build a formatted table.
    headers = ("Name", "Version", "Source", "Module", "Status", "Registrations")
    # Compute column widths from data.
    col_name = max(len(headers[0]), *(len(r["name"]) for r in rows))
    col_ver = max(len(headers[1]), *(len(r["version"]) for r in rows))
    col_src = max(len(headers[2]), *(len(r["source"]) for r in rows))
    col_mod = max(len(headers[3]), *(len(r["module"]) for r in rows))
    col_stat = max(len(headers[4]), *(len(r["status"]) for r in rows))

    def _reg_summary(regs: dict[str, int]) -> str:
        if not regs:
            return "-"
        return ", ".join(f"{v} {k}" for k, v in regs.items())

    col_reg = max(
        len(headers[5]), *(_len_reg_summary(r["registrations"]) for r in rows)
    )

    fmt = (
        f"  {{:<{col_name}}}  {{:<{col_ver}}}  {{:<{col_src}}}  "
        f"{{:<{col_mod}}}  {{:<{col_stat}}}  {{}}"
    )
    header_line = fmt.format(*headers)
    separator = "  " + "  ".join(
        "-" * w for w in (col_name, col_ver, col_src, col_mod, col_stat, col_reg)
    )

    print(f"Installed plugins ({len(rows)}):\n")
    print(header_line)
    print(separator)
    for r in rows:
        print(
            fmt.format(
                r["name"],
                r["version"],
                r["source"],
                r["module"],
                r["status"],
                _reg_summary(r["registrations"]),
            )
        )

    # Show errors for failed plugins below the table.
    failed = [r for r in rows if r["status"] == "failed"]
    if failed:
        print()
        for r in failed:
            print(f"  ! {r['name']}: {r['error']}")


def _detect_install_source(dist: Any) -> str:
    """Determine whether a distribution was installed as editable or from PyPI.

    Checks for ``direct_url.json`` (PEP 610) — editable installs set
    ``dir_info.editable = true``. Falls back to legacy ``.egg-link``
    detection for older setuptools editable installs.
    """
    if dist is None:
        return "unknown"

    # PEP 610: read direct_url.json from distribution metadata.
    try:
        direct_url_text = dist.read_text("direct_url.json")
        if direct_url_text:
            direct_url = json.loads(direct_url_text)
            dir_info = direct_url.get("dir_info", {})
            if dir_info.get("editable", False):
                return "editable"
            # A direct_url.json without editable flag means a direct
            # install (VCS, local path, URL) but not editable.
            return "direct"
    except (FileNotFoundError, json.JSONDecodeError):
        pass

    # Legacy: check for .egg-link files (setuptools editable < PEP 660).
    dist_name = getattr(dist, "name", None) or getattr(dist, "_name", None)
    if dist_name:
        import site  # noqa: PLC0415

        for site_dir in site.getsitepackages() + [site.getusersitepackages()]:
            egg_link = Path(site_dir) / f"{dist_name}.egg-link"
            if egg_link.exists():
                return "editable"

    return "pypi"


def _len_reg_summary(regs: dict[str, int]) -> int:
    """Compute display length of the registration summary string."""
    if not regs:
        return 1  # "-"
    return len(", ".join(f"{v} {k}" for k, v in regs.items()))


# ---------------------------------------------------------------------------
# scaffold-fragment
# ---------------------------------------------------------------------------


def _parse_backends(raw: str | None) -> tuple[str, ...]:
    """Parse ``--backends python,node,rust`` into a validated tuple.

    Empty / ``None`` yields the default (``_DEFAULT_BACKENDS``). Unknown
    backends raise a hard error before we touch the filesystem so the
    user doesn't end up with a half-rendered tree.
    """
    if not raw:
        return _DEFAULT_BACKENDS
    requested = tuple(b.strip().lower() for b in raw.split(",") if b.strip())
    if not requested:
        return _DEFAULT_BACKENDS
    unknown = [b for b in requested if b not in _BACKEND_CONST]
    if unknown:
        print(
            f"scaffold-fragment: unknown backend(s): {', '.join(unknown)}. "
            f"Choose from: {', '.join(_DEFAULT_BACKENDS)}",
            file=sys.stderr,
        )
        sys.exit(2)
    # Preserve user order but drop dupes.
    seen: set[str] = set()
    deduped: list[str] = []
    for b in requested:
        if b not in seen:
            seen.add(b)
            deduped.append(b)
    return tuple(deduped)


def _validate_fragment_name(name: str) -> None:
    """Reject names that wouldn't survive a Python identifier check.

    Fragment names get embedded in generated Python source
    (``register_<name>``, ``"<name>"`` in the Fragment constructor),
    used as directory names, and used as registry keys. ``isidentifier``
    + non-keyword is the smallest screen that catches the common bugs
    (hyphens, leading digits, reserved words) before we render anything.
    """
    if not name:
        raise ValueError("fragment name is empty")
    if not name.isidentifier():
        raise ValueError(
            f"fragment name {name!r} is not a valid Python identifier "
            "(letters/digits/underscores, may not start with a digit)"
        )
    if keyword.iskeyword(name):
        raise ValueError(f"fragment name {name!r} is a Python reserved word")


def _default_output_dir(name: str) -> Path:
    """Plan-A default output path: a sibling ``plugins/`` tree.

    Matches the layout the example plugin uses (``src/forge_plugin_<name>/
    fragments/<name>/``) so a plugin author can scaffold a fragment and
    then drop the surrounding ``forge-plugin-<name>`` package around it
    with minimal moving parts.
    """
    return (
        Path.cwd()
        / "plugins"
        / f"forge-plugin-{name}"
        / f"forge_plugin_{name}"
        / "fragments"
        / name
    )


def _scaffold_fragment(
    *,
    name: str,
    output_dir: str | None,
    backends: Sequence[str],
    force: bool,
) -> None:
    """Render the fragment-skeleton template tree into ``output_dir``."""
    try:
        _validate_fragment_name(name)
    except ValueError as exc:
        print(f"scaffold-fragment: {exc}", file=sys.stderr)
        sys.exit(2)

    target = Path(output_dir).resolve() if output_dir else _default_output_dir(name)

    # Codex Phase B round 1 follow-up: defensive check for the case where
    # the user passes an existing FILE path (not a dir). `iterdir()` would
    # raise NotADirectoryError uncontrolled; surface a typed CLI error.
    if target.exists() and not target.is_dir():
        print(
            f"scaffold-fragment: --output-dir target exists but is not a directory: {target}",
            file=sys.stderr,
        )
        sys.exit(2)

    if target.exists() and any(target.iterdir()):
        if not force:
            print(
                f"scaffold-fragment: refusing to overwrite non-empty directory: {target}\n"
                f"  Re-run with --force to overwrite, or pick a different --output-dir.",
                file=sys.stderr,
            )
            sys.exit(1)
        # --force: wipe the existing tree so the render is deterministic.
        shutil.rmtree(target)

    target.mkdir(parents=True, exist_ok=True)

    rendered_files = _render_skeleton(target, name=name, backends=tuple(backends))

    # User-visible progress — mirrors the existing `forge --plugins list`
    # output style (plain text, no colour, one line per item).
    print(f"Scaffolded fragment '{name}' at {target}")
    print(f"  backends: {', '.join(backends)}")
    print(f"  files ({len(rendered_files)}):")
    for path in rendered_files:
        print(f"    - {path.relative_to(target)}")
    print()
    print("Next steps:")
    print(f"  1. Edit {target / 'fragments.py'} — wire register_{name}() into your plugin.")
    print(f"  2. Register an Option whose enables map points at '{name}'.")
    print("  3. Author the per-backend inject.yaml entries.")
    print("  4. See docs/plugin-development.md for the full guide.")


def _render_skeleton(
    target: Path,
    *,
    name: str,
    backends: tuple[str, ...],
) -> list[Path]:
    """Walk the template tree under ``fragment_skeleton/`` and render.

    Files with the ``.jinja`` suffix are rendered through Jinja2 and the
    suffix is stripped on write. Files without the suffix are copied
    verbatim. Per-backend subdirectories (``python/``, ``node/``,
    ``rust/``) are only emitted for backends listed in ``backends``.
    """
    import jinja2  # noqa: PLC0415 — lazy: import only when scaffolding.

    context: dict[str, Any] = {
        "name": name,
        "backends": list(backends),
        "backend_const": _BACKEND_CONST.get,
    }

    skeleton_root = resources.files("forge.cli.scaffold").joinpath("fragment_skeleton")
    # ``resources.files`` returns a Traversable, which on a real
    # filesystem install is a concrete ``Path`` — we need ``Path`` for
    # ``rglob`` and ``relative_to``. Materialise via ``as_file`` for
    # wheel-install safety (no-op on editable installs).
    rendered: list[Path] = []
    with resources.as_file(skeleton_root) as root_path:
        # The package-data layout we ship per_backend dirs as
        # ``python/``, ``node/``, ``rust/``. Skip the ones the user
        # opted out of via --backends.
        backend_set = set(backends)
        all_known = set(_DEFAULT_BACKENDS)

        env = jinja2.Environment(
            keep_trailing_newline=True,
            undefined=jinja2.StrictUndefined,
            autoescape=False,  # noqa: S701 — rendering source code, not HTML.
        )

        for src in sorted(root_path.rglob("*")):
            if src.is_dir():
                continue
            rel = src.relative_to(root_path)
            # First path component decides whether this is a per-backend
            # asset and, if so, whether to skip it.
            head = rel.parts[0]
            if head in all_known and head not in backend_set:
                continue

            dest_rel = _strip_jinja_suffix(rel)
            dest = target / dest_rel
            dest.parent.mkdir(parents=True, exist_ok=True)

            if src.suffix == ".jinja":
                template = env.from_string(src.read_text(encoding="utf-8"))
                dest.write_text(template.render(**context), encoding="utf-8")
            else:
                shutil.copy2(src, dest)
            rendered.append(dest)

    return rendered


def _strip_jinja_suffix(rel: Path) -> Path:
    """Drop a trailing ``.jinja`` extension from a relative template path."""
    if rel.suffix == ".jinja":
        return rel.with_suffix("")
    return rel
