# -- Build stage --
FROM ghcr.io/cirruslabs/flutter:stable AS builder
WORKDIR /app

COPY . .
RUN flutter pub get
RUN flutter build web --release

# -- Runtime stage --
FROM nginx:alpine

COPY --from=builder /app/build/web /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
