"""Tests for the AG-UI event-union codegen (Theme 2B).

The codegen synthesises a ``kind`` discriminator from each schema's
PascalCase title and assembles a single discriminated union across
all seven ``ui-protocol`` schemas. The invariants this test file
defends are:

    * Every shipped schema appears in the emitted union (drift between
      schema set and union is impossible by construction — the test
      asserts the construction property).
    * The synthesised ``kind`` slug matches the schema title's
      kebab-case form (so reading the wire and inferring the schema is
      a one-step process).
    * Emit is byte-stable (the load-bearing invariant for codegen).
    * The ``assertUnreachable`` helper is present in the TS output and
      the Dart sealed class enforces exhaustiveness at the language
      level.
    * The Pydantic output round-trips through Pydantic v2's
      discriminated-union machinery — i.e. it's not just syntactically
      valid Python, it's a real working union.

The TS output isn't compiled here (no Node toolchain available in the
forge test env), but ``ast``-style structural assertions on shape +
the Pydantic runtime check together cover the surface.
"""

from __future__ import annotations

import ast
import sys
import tempfile
from pathlib import Path

import pytest

from forge.codegen.event_union import (
    DEFAULT_SCHEMA_ROOT,
    SCHEMA_VERSION,
    _kind_for,
    _kinds_list,
    _pascal_to_kebab,
    emit_dart,
    emit_pydantic,
    emit_typescript,
    load_event_schemas,
    regenerate_packages,
)
from forge.codegen.ui_protocol import emit_pydantic as emit_ui_pydantic

# Every schema title shipped under ``forge/templates/_shared/ui-protocol/``.
# Pinning the set here means adding a new schema requires updating this
# list — the test will fail loudly until the new variant is consciously
# admitted into the union.
_EXPECTED_TITLES: frozenset[str] = frozenset(
    {
        "AgUiPayload",
        "AgentState",
        "HitlResponse",
        "McpExtPayload",
        "ToolCallInfo",
        "UserPromptPayload",
        "WorkspaceActivity",
    }
)

# Title → expected synthesised kind slug. Sanity-check the slug derivation
# at the test level so a regression in ``_pascal_to_kebab`` is caught
# without needing to read the emitted output.
_EXPECTED_KINDS: dict[str, str] = {
    "AgUiPayload": "ag-ui-payload",
    "AgentState": "agent-state",
    "HitlResponse": "hitl-response",
    "McpExtPayload": "mcp-ext-payload",
    "ToolCallInfo": "tool-call-info",
    "UserPromptPayload": "user-prompt-payload",
    "WorkspaceActivity": "workspace-activity",
}


class TestSlugDerivation:
    def test_pascal_to_kebab_handles_acronyms(self) -> None:
        # Consecutive uppercase letters are one word ('AG' in 'AgUi').
        assert _pascal_to_kebab("AgUiPayload") == "ag-ui-payload"
        assert _pascal_to_kebab("McpExtPayload") == "mcp-ext-payload"

    def test_pascal_to_kebab_simple(self) -> None:
        assert _pascal_to_kebab("HitlResponse") == "hitl-response"
        assert _pascal_to_kebab("UserPromptPayload") == "user-prompt-payload"

    def test_kind_for_uses_title(self) -> None:
        schemas = load_event_schemas()
        for s in schemas:
            assert _kind_for(s) == _EXPECTED_KINDS[s.title]


class TestLoadEventSchemas:
    def test_loads_all_seven_shipped_schemas(self) -> None:
        schemas = load_event_schemas()
        assert {s.title for s in schemas} == _EXPECTED_TITLES

    def test_default_root_points_at_ui_protocol_dir(self) -> None:
        assert DEFAULT_SCHEMA_ROOT.is_dir()
        assert (DEFAULT_SCHEMA_ROOT / "ag_ui_payload.schema.json").is_file()


class TestEmitTypescript:
    def test_banner_is_autogenerated(self) -> None:
        out = emit_typescript(load_event_schemas())
        assert "AUTOGENERATED — DO NOT EDIT." in out
        assert "forge/templates/_shared/ui-protocol" in out
        assert f"Schema version: {SCHEMA_VERSION}" in out

    def test_every_schema_emits_variant_interface(self) -> None:
        out = emit_typescript(load_event_schemas())
        for title in _EXPECTED_TITLES:
            assert f"export interface {title} " in out or f"export interface {title}{{" in out, (
                f"missing inlined interface for {title}"
            )

    def test_every_schema_emits_with_kind_alias(self) -> None:
        out = emit_typescript(load_event_schemas())
        for title, kind in _EXPECTED_KINDS.items():
            expected = f'export type {title}WithKind = {title} & {{ kind: "{kind}" }};'
            assert expected in out, f"missing intersection alias: {expected}"

    def test_union_type_lists_every_variant(self) -> None:
        out = emit_typescript(load_event_schemas())
        assert "export type AgUiEvent =" in out
        for title in _EXPECTED_TITLES:
            assert f"| {title}WithKind" in out, f"variant {title}WithKind missing from union"

    def test_kind_literal_union_lists_every_kind(self) -> None:
        out = emit_typescript(load_event_schemas())
        assert "export type AgUiEventKind =" in out
        for kind in _EXPECTED_KINDS.values():
            assert f'"{kind}"' in out, f"missing kind literal: {kind}"

    def test_assert_unreachable_is_present(self) -> None:
        out = emit_typescript(load_event_schemas())
        assert "export function assertUnreachable(_: never): never" in out
        # The thrown error must carry a message that names the contract —
        # this is the diagnostic future maintainers see.
        assert "Non-exhaustive AG-UI event union" in out

    def test_get_event_kind_helper_is_present(self) -> None:
        out = emit_typescript(load_event_schemas())
        assert "export function getEventKind(event: AgUiEvent): AgUiEventKind" in out


class TestEmitDart:
    def test_banner_is_autogenerated(self) -> None:
        out = emit_dart(load_event_schemas())
        assert "AUTOGENERATED — DO NOT EDIT." in out
        assert "forge/templates/_shared/ui-protocol" in out
        assert f"Schema version: {SCHEMA_VERSION}" in out

    def test_sealed_class_declared(self) -> None:
        out = emit_dart(load_event_schemas())
        assert "sealed class AgUiEvent {" in out
        # Subclasses must declare the kind getter — exhaustiveness on the
        # sealed class is the Dart equivalent of TS's assertUnreachable.
        assert "String get kind;" in out

    def test_every_variant_is_a_final_subclass(self) -> None:
        out = emit_dart(load_event_schemas())
        for title, kind in _EXPECTED_KINDS.items():
            assert f"final class {title}Event extends AgUiEvent {{" in out, (
                f"missing final class {title}Event"
            )
            assert f"String get kind => '{kind}';" in out, (
                f"missing kind getter for {title}Event"
            )

    def test_every_variant_carries_payload_field(self) -> None:
        out = emit_dart(load_event_schemas())
        for title in _EXPECTED_TITLES:
            assert f"final {title} payload;" in out

    def test_parse_factory_signature_matches_ag_ui_client_contract(self) -> None:
        """The Dart `AgUiClient` in `packages/forge-canvas-dart/lib/src/ag_ui_client.dart`
        expects `AgUiEvent.parse` with this exact signature — see line 24
        of that file. If we drop or rename the factory, the canvas-dart
        package no longer wires up cleanly to its own client.
        """
        out = emit_dart(load_event_schemas())
        assert "static AgUiEvent? parse(Map<String, dynamic> json) {" in out

    def test_parse_factory_reads_canonical_kind_discriminator(self) -> None:
        out = emit_dart(load_event_schemas())
        # The factory must read the canonical `kind` field, not `type` —
        # that's the whole point of Initiative #4.
        assert "json['kind']" in out
        # And must reject non-string discriminators (defensive parsing
        # against malformed frames).
        assert "if (kind is! String) return null;" in out

    def test_parse_factory_dispatches_every_kind(self) -> None:
        """Every shipped schema must have a `case '<kind>'` branch
        that constructs its sealed-class wrapper from the payload's
        `fromJson`. Missing a branch silently drops events of that
        kind on the floor — exactly the failure mode we're guarding
        against.
        """
        out = emit_dart(load_event_schemas())
        for title, kind in _EXPECTED_KINDS.items():
            case_line = f"case '{kind}':"
            ctor_line = f"return {title}Event({title}.fromJson(json));"
            assert case_line in out, f"parse factory missing case for {kind!r}"
            assert ctor_line in out, f"parse factory missing constructor for {title}Event"

    def test_parse_factory_returns_null_on_unknown_kind(self) -> None:
        out = emit_dart(load_event_schemas())
        assert "default:" in out
        assert "return null;" in out


class TestEmitPydantic:
    def test_banner_is_autogenerated(self) -> None:
        out = emit_pydantic(load_event_schemas())
        assert "AUTOGENERATED — DO NOT EDIT." in out
        assert "forge/templates/_shared/ui-protocol" in out
        assert f"Schema version: {SCHEMA_VERSION}" in out

    def test_imports_variant_classes_from_ui_protocol(self) -> None:
        out = emit_pydantic(load_event_schemas())
        assert "from .ui_protocol import (" in out
        for title in _EXPECTED_TITLES:
            assert f"    {title}," in out

    def test_every_variant_emits_event_wrapper(self) -> None:
        out = emit_pydantic(load_event_schemas())
        for title, kind in _EXPECTED_KINDS.items():
            wrapper = f"{title}Event"
            assert f"class {wrapper}(BaseModel):" in out
            assert f'kind: Literal["{kind}"] = "{kind}"' in out
            assert f"payload: {title}" in out

    def test_union_is_discriminated(self) -> None:
        out = emit_pydantic(load_event_schemas())
        assert "AgUiEvent = Annotated[" in out
        assert 'Field(discriminator="kind"),' in out
        assert "AgUiEventAdapter: TypeAdapter[AgUiEvent]" in out

    def test_emitted_code_is_syntactically_valid_python(self) -> None:
        out = emit_pydantic(load_event_schemas())
        # If this raises, the emitter produced something Python can't
        # even parse, never mind import.
        ast.parse(out)

    def test_pydantic_union_validates_at_runtime(self, tmp_path: Path) -> None:
        """End-to-end: the emitted union must actually load and validate.

        Build a tiny on-disk package: ``ui_protocol.py`` from the 1B
        emitter, ``canvas_events.py`` from the 2B emitter, then import
        the adapter and round-trip a hand-rolled event through it.
        """
        pkg = tmp_path / "ev_pkg"
        pkg.mkdir()
        (pkg / "__init__.py").write_text("", encoding="utf-8")
        (pkg / "ui_protocol.py").write_text(emit_ui_pydantic(load_event_schemas()), encoding="utf-8")
        (pkg / "canvas_events.py").write_text(emit_pydantic(load_event_schemas()), encoding="utf-8")

        sys.path.insert(0, str(tmp_path))
        try:
            from ev_pkg.canvas_events import AgUiEventAdapter  # type: ignore[import-not-found]

            # Discriminator picks the right variant.
            ev = AgUiEventAdapter.validate_python(
                {
                    "kind": "hitl-response",
                    "payload": {"tool_call_id": "abc", "answer": "yes"},
                }
            )
            assert type(ev).__name__ == "HitlResponseEvent"
            assert ev.payload.tool_call_id == "abc"

            # Wrong kind → validation error (negative case).
            with pytest.raises(Exception):  # pydantic ValidationError
                AgUiEventAdapter.validate_python(
                    {"kind": "nonexistent-kind", "payload": {}}
                )
        finally:
            sys.path.remove(str(tmp_path))
            # Defensive: drop cached modules so a subsequent invocation
            # doesn't see this run's import.
            for mod_name in [
                m
                for m in list(sys.modules)
                if m == "ev_pkg" or m.startswith("ev_pkg.")
            ]:
                del sys.modules[mod_name]


class TestIdempotency:
    """Codegen MUST be byte-stable across runs — same invariant as 1B."""

    def test_typescript_is_byte_equal(self) -> None:
        a = emit_typescript(load_event_schemas())
        b = emit_typescript(load_event_schemas())
        assert a == b

    def test_dart_is_byte_equal(self) -> None:
        a = emit_dart(load_event_schemas())
        b = emit_dart(load_event_schemas())
        assert a == b

    def test_pydantic_is_byte_equal(self) -> None:
        a = emit_pydantic(load_event_schemas())
        b = emit_pydantic(load_event_schemas())
        assert a == b


class TestRegeneratePackages:
    """The CLI entry point writes the canvas-package event-union files."""

    def test_writes_every_target(self, tmp_path: Path) -> None:
        written = regenerate_packages(repo_root=tmp_path)
        rels = {p.relative_to(tmp_path).as_posix() for p in written}
        assert rels == {
            "packages/canvas-vue/src/generated/events.ts",
            "packages/canvas-svelte/src/generated/events.ts",
            "packages/forge-canvas-dart/lib/src/generated/events.dart",
        }

    def test_outputs_are_byte_stable(self, tmp_path: Path) -> None:
        regenerate_packages(repo_root=tmp_path)
        snapshot = {
            p: (tmp_path / p).read_bytes()
            for p in (
                "packages/canvas-vue/src/generated/events.ts",
                "packages/canvas-svelte/src/generated/events.ts",
                "packages/forge-canvas-dart/lib/src/generated/events.dart",
            )
        }
        regenerate_packages(repo_root=tmp_path)
        for rel, expected in snapshot.items():
            assert (tmp_path / rel).read_bytes() == expected, f"{rel} changed across runs"

    def test_vue_and_svelte_emit_same_typescript(self, tmp_path: Path) -> None:
        # Same single-source invariant as canvas-props: vue and svelte
        # must agree byte-for-byte on the TS event-union module.
        regenerate_packages(repo_root=tmp_path)
        vue = (tmp_path / "packages/canvas-vue/src/generated/events.ts").read_text()
        svelte = (tmp_path / "packages/canvas-svelte/src/generated/events.ts").read_text()
        assert vue == svelte


class TestExhaustiveCoverage:
    """The union must cover every shipped schema — drift detection."""

    def test_kinds_list_matches_loaded_schemas(self) -> None:
        schemas = load_event_schemas()
        kinds = _kinds_list(schemas)
        assert {title for title, _ in kinds} == _EXPECTED_TITLES

    def test_every_loaded_schema_appears_in_typescript_union(self) -> None:
        schemas = load_event_schemas()
        out = emit_typescript(schemas)
        for s in schemas:
            kind = _kind_for(s)
            # The kind slug AND the title must both be referenced — the
            # type alias declaration is the load-bearing line.
            assert f'kind: "{kind}"' in out, f"kind {kind} missing from union"
            assert f"{s.title}WithKind" in out, f"variant {s.title}WithKind missing"

    def test_every_loaded_schema_appears_in_dart_sealed(self) -> None:
        schemas = load_event_schemas()
        out = emit_dart(schemas)
        for s in schemas:
            assert f"class {s.title}Event extends AgUiEvent" in out

    def test_every_loaded_schema_appears_in_pydantic_union(self) -> None:
        schemas = load_event_schemas()
        out = emit_pydantic(schemas)
        for s in schemas:
            kind = _kind_for(s)
            assert f'Literal["{kind}"]' in out


class TestSchemaVersion:
    def test_schema_version_is_int(self) -> None:
        assert isinstance(SCHEMA_VERSION, int)
        assert SCHEMA_VERSION >= 1
