"""Integration test for the codegen pipeline (Integration I1)."""

from __future__ import annotations

from pathlib import Path

from forge.codegen.pipeline import run_codegen
from forge.config import (
    BackendConfig,
    BackendLanguage,
    FrontendConfig,
    FrontendFramework,
    ProjectConfig,
)


def _make_python_project(tmp_path: Path, frontend: FrontendFramework | None = None) -> tuple[ProjectConfig, Path]:
    project_root = tmp_path / "codegen_demo"
    project_root.mkdir()
    fe = None
    if frontend and frontend != FrontendFramework.NONE:
        fe = FrontendConfig(
            framework=frontend,
            project_name="codegen_demo",
            description="test",
            include_chat=True,
        )
    config = ProjectConfig(
        project_name="codegen_demo",
        backends=[
            BackendConfig(
                name="api",
                project_name="codegen_demo",
                language=BackendLanguage.PYTHON,
                features=["items"],
            )
        ],
        frontend=fe,
    )
    return config, project_root


class TestUiProtocolEmission:
    def test_emits_pydantic_into_python_backend(self, tmp_path: Path) -> None:
        config, project_root = _make_python_project(tmp_path)
        run_codegen(config, project_root)
        target = project_root / "services" / "api" / "src" / "app" / "domain" / "ui_protocol.py"
        assert target.is_file()
        body = target.read_text(encoding="utf-8")
        assert "class AgentState(BaseModel):" in body

    def test_emits_ts_into_vue_frontend(self, tmp_path: Path) -> None:
        config, project_root = _make_python_project(tmp_path, FrontendFramework.VUE)
        run_codegen(config, project_root)
        target = (
            project_root
            / config.frontend_slug
            / "src"
            / "features"
            / "ai_chat"
            / "ui_protocol.gen.ts"
        )
        assert target.is_file()
        assert "export interface AgentState" in target.read_text(encoding="utf-8")

    def test_emits_dart_into_flutter_frontend(self, tmp_path: Path) -> None:
        config, project_root = _make_python_project(tmp_path, FrontendFramework.FLUTTER)
        run_codegen(config, project_root)
        target = (
            project_root
            / config.frontend_slug
            / "lib"
            / "src"
            / "features"
            / "chat"
            / "domain"
            / "ui_protocol.gen.dart"
        )
        assert target.is_file()
        assert "class AgentState {" in target.read_text(encoding="utf-8")


class TestCanvasManifest:
    def test_writes_manifest_into_vue_public(self, tmp_path: Path) -> None:
        config, project_root = _make_python_project(tmp_path, FrontendFramework.VUE)
        run_codegen(config, project_root)
        target = project_root / config.frontend_slug / "public" / "canvas.manifest.json"
        assert target.is_file()
        body = target.read_text(encoding="utf-8")
        assert "DataTable" in body
        assert "CodeViewer" in body

    def test_writes_manifest_into_flutter_assets(self, tmp_path: Path) -> None:
        config, project_root = _make_python_project(tmp_path, FrontendFramework.FLUTTER)
        run_codegen(config, project_root)
        target = project_root / config.frontend_slug / "assets" / "canvas.manifest.json"
        assert target.is_file()

    def test_no_manifest_without_frontend(self, tmp_path: Path) -> None:
        config, project_root = _make_python_project(tmp_path, FrontendFramework.NONE)
        run_codegen(config, project_root)
        # No frontend, no manifest.
        assert not any(project_root.rglob("canvas.manifest.json"))


class TestCanvasPropsPydantic:
    """Theme 1B-C3 — Pydantic models for canvas component props land
    next to ``ui_protocol.py`` in every Python backend's ``domain/``
    directory.
    """

    def test_emits_canvas_props_into_python_backend(self, tmp_path: Path) -> None:
        config, project_root = _make_python_project(tmp_path)
        run_codegen(config, project_root)
        target = (
            project_root / "services" / "api" / "src" / "app" / "domain" / "canvas_props.py"
        )
        assert target.is_file()
        body = target.read_text(encoding="utf-8")
        # Every shipped canvas schema must appear as a BaseModel class.
        for cls in (
            "CodeViewerProps",
            "DataTableProps",
            "DynamicFormProps",
            "ReportProps",
            "WorkflowDiagramProps",
        ):
            assert f"class {cls}(BaseModel):" in body, f"missing {cls} in canvas_props.py"
        # Banner must mark it as autogenerated + point at the canvas
        # schema directory.
        assert "AUTOGENERATED" in body
        assert "canvas-components" in body

    def test_no_canvas_props_without_python_backend(self, tmp_path: Path) -> None:
        # No Python backends → no canvas_props.py to write.
        project_root = tmp_path / "node_only"
        project_root.mkdir()
        config = ProjectConfig(
            project_name="node_only",
            backends=[
                BackendConfig(
                    name="api",
                    project_name="node_only",
                    language=BackendLanguage.NODE,
                    features=["items"],
                )
            ],
            frontend=None,
        )
        run_codegen(config, project_root)
        assert not any(project_root.rglob("canvas_props.py"))

    def test_idempotent_across_two_runs(self, tmp_path: Path) -> None:
        # Running run_codegen twice must produce byte-identical output.
        # This is the load-bearing invariant — without it, every diff
        # would surface noise from non-deterministic emit order.
        config, project_root = _make_python_project(tmp_path)
        run_codegen(config, project_root)
        target = (
            project_root / "services" / "api" / "src" / "app" / "domain" / "canvas_props.py"
        )
        first = target.read_bytes()
        run_codegen(config, project_root)
        assert target.read_bytes() == first


class TestCanvasEventsUnion:
    """Theme 2B + Initiative #4 — discriminated event-union Pydantic
    module + per-frontend TS/Dart output.

    The event union lands in ``services/<backend>/src/app/domain/canvas_events.py``
    for every Python backend. All three built-in frontends
    (Vue/Svelte/Flutter) ship the same union, written to a
    framework-specific path under the frontend's layout.
    """

    def test_emits_canvas_events_into_python_backend(self, tmp_path: Path) -> None:
        config, project_root = _make_python_project(tmp_path)
        run_codegen(config, project_root)
        target = (
            project_root / "services" / "api" / "src" / "app" / "domain" / "canvas_events.py"
        )
        assert target.is_file()
        body = target.read_text(encoding="utf-8")
        assert "AgUiEvent = Annotated[" in body
        assert "AgUiEventAdapter" in body
        # Every shipped ui-protocol schema must appear as an Event wrapper.
        for cls in (
            "AgUiPayloadEvent",
            "AgentStateEvent",
            "HitlResponseEvent",
            "McpExtPayloadEvent",
            "ToolCallInfoEvent",
            "UserPromptPayloadEvent",
            "WorkspaceActivityEvent",
        ):
            assert f"class {cls}(BaseModel):" in body, f"missing {cls}"

    def test_emits_events_gen_ts_into_vue_template(self, tmp_path: Path) -> None:
        config, project_root = _make_python_project(tmp_path, FrontendFramework.VUE)
        run_codegen(config, project_root)
        target = (
            project_root / config.frontend_slug / "src" / "features" / "ai_chat" / "events.gen.ts"
        )
        assert target.is_file()
        body = target.read_text(encoding="utf-8")
        assert "export type AgUiEvent =" in body
        assert "export function assertUnreachable" in body

    def test_emits_events_gen_ts_into_svelte_template(self, tmp_path: Path) -> None:
        # Initiative #4: Svelte now ships the same event union as Vue.
        # The path mirrors Svelte's ui_protocol layout
        # (``src/lib/features/chat/``) — adjacent to the payload types
        # it discriminates over.
        config, project_root = _make_python_project(tmp_path, FrontendFramework.SVELTE)
        run_codegen(config, project_root)
        target = (
            project_root
            / config.frontend_slug
            / "src"
            / "lib"
            / "features"
            / "chat"
            / "events.gen.ts"
        )
        assert target.is_file(), "Svelte should now ship events.gen.ts (Initiative #4)"
        body = target.read_text(encoding="utf-8")
        assert "export type AgUiEvent =" in body
        assert "export function assertUnreachable" in body

    def test_emits_events_gen_dart_into_flutter_template(self, tmp_path: Path) -> None:
        # Initiative #4: Flutter's Dart sealed class lands next to its
        # ui_protocol payload types under ``domain/``.
        config, project_root = _make_python_project(tmp_path, FrontendFramework.FLUTTER)
        run_codegen(config, project_root)
        target = (
            project_root
            / config.frontend_slug
            / "lib"
            / "src"
            / "features"
            / "chat"
            / "domain"
            / "events.gen.dart"
        )
        assert target.is_file(), "Flutter should now ship events.gen.dart (Initiative #4)"
        body = target.read_text(encoding="utf-8")
        assert "sealed class AgUiEvent {" in body
        # The static parse factory is the contract the AgUiClient consumes.
        assert "static AgUiEvent? parse(Map<String, dynamic> json)" in body

    def test_idempotent_across_two_runs(self, tmp_path: Path) -> None:
        config, project_root = _make_python_project(tmp_path, FrontendFramework.VUE)
        run_codegen(config, project_root)
        py_target = (
            project_root / "services" / "api" / "src" / "app" / "domain" / "canvas_events.py"
        )
        ts_target = (
            project_root / config.frontend_slug / "src" / "features" / "ai_chat" / "events.gen.ts"
        )
        first_py = py_target.read_bytes()
        first_ts = ts_target.read_bytes()
        run_codegen(config, project_root)
        assert py_target.read_bytes() == first_py
        assert ts_target.read_bytes() == first_ts


class TestSharedEnums:
    def test_item_status_lands_in_python_backend(self, tmp_path: Path) -> None:
        config, project_root = _make_python_project(tmp_path)
        run_codegen(config, project_root)
        target = (
            project_root / "services" / "api" / "src" / "app" / "domain" / "enums" / "item_status.py"
        )
        assert target.is_file()
        body = target.read_text(encoding="utf-8")
        assert "class ItemStatus(str, Enum):" in body

    def test_approval_mode_lands_in_vue_shared(self, tmp_path: Path) -> None:
        config, project_root = _make_python_project(tmp_path, FrontendFramework.VUE)
        run_codegen(config, project_root)
        target = (
            project_root
            / config.frontend_slug
            / "src"
            / "shared"
            / "enums"
            / "approval_mode.ts"
        )
        assert target.is_file()
        body = target.read_text(encoding="utf-8")
        assert "ApprovalMode" in body


class TestProvenance:
    def test_codegen_writes_provenance_records(self, tmp_path: Path) -> None:
        from forge.sync.provenance import ProvenanceCollector  # noqa: PLC0415

        config, project_root = _make_python_project(tmp_path, FrontendFramework.VUE)
        collector = ProvenanceCollector(project_root=project_root)
        run_codegen(config, project_root, collector=collector)
        # Expect at least the UI-protocol emissions and canvas manifest
        # to have provenance entries.
        assert any(
            "ui_protocol" in key for key in collector.records
        ), f"no ui_protocol key in provenance: {list(collector.records)[:10]}"
        assert any("canvas.manifest" in key for key in collector.records)
