"""Tests for the canvas-props schema codegen (Theme 1B).

The emitter is a thin wrapper over :mod:`forge.codegen.ui_protocol` — its
job is to:

    * load the right schema directory
      (``forge/templates/_shared/canvas-components/*.props.schema.json``)
    * stamp the right banner so generated files point at the canvas
      sources, not the ui-protocol ones
    * carry a ``schema_version`` tag that satisfies the
      ``pipeline.py:216`` TODO

These tests assert exactly those properties, plus byte-stable idempotency
(running the emitter twice produces the same bytes) — the load-bearing
invariant for codegen at large.

Today the module emits TypeScript only. Dart and Pydantic land in
follow-on commits of the same theme; corresponding tests land with them.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from forge.codegen.canvas_props import (
    DEFAULT_SCHEMA_ROOT,
    SCHEMA_VERSION,
    emit_typescript,
    load_canvas_schemas,
    regenerate_packages,
)

# Per-schema fields that must round-trip into every generated target. The
# tuples are ordered (schema_title, [required_field_names...]). Every
# field listed here must show up by string presence in TS / Dart / Py
# output — sufficient as a codegen contract test (a stronger test would
# parse the emitted source, which the existing ui_protocol tests already
# do at the helper level).
_EXPECTED_FIELDS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("CodeViewerProps", ("code", "language", "filename", "showLineNumbers")),
    ("DataTableProps", ("columns", "rows", "pageSize")),
    ("DynamicFormProps", ("title", "fields", "submitLabel", "cancelLabel")),
    ("ReportProps", ("title", "markdown")),
    ("WorkflowDiagramProps", ("nodes", "edges")),
)


class TestLoadCanvasSchemas:
    def test_loads_all_five_shipped_schemas(self) -> None:
        schemas = load_canvas_schemas()
        assert {s.title for s in schemas} == {
            "CodeViewerProps",
            "DataTableProps",
            "DynamicFormProps",
            "ReportProps",
            "WorkflowDiagramProps",
        }

    def test_default_root_points_at_canvas_components_dir(self) -> None:
        # Sanity: the constant must match where the schemas actually
        # live, or downstream emit code silently emits nothing.
        assert DEFAULT_SCHEMA_ROOT.is_dir()
        assert (DEFAULT_SCHEMA_ROOT / "DataTable.props.schema.json").is_file()


class TestEmitTypescript:
    def test_banner_is_autogenerated(self) -> None:
        out = emit_typescript(load_canvas_schemas())
        assert "AUTOGENERATED — DO NOT EDIT." in out
        assert "forge/templates/_shared/canvas-components" in out
        assert f"Schema version: {SCHEMA_VERSION}" in out

    def test_every_schema_emits_interface(self) -> None:
        out = emit_typescript(load_canvas_schemas())
        for title, _ in _EXPECTED_FIELDS:
            assert f"export interface {title}" in out, f"missing TS interface {title}"

    def test_every_field_appears(self) -> None:
        out = emit_typescript(load_canvas_schemas())
        for title, fields in _EXPECTED_FIELDS:
            for f in fields:
                assert f in out, f"TS output missing field {f} (from {title})"

    def test_enum_becomes_literal_union(self) -> None:
        # DynamicForm.fields[].type is enum: ["text", ..., "textarea"]
        out = emit_typescript(load_canvas_schemas())
        assert '"text" | "number" | "password"' in out


class TestIdempotency:
    """Codegen MUST be byte-stable across runs.

    A flaky emitter (dict iteration order leaking, timestamps, anything)
    poisons every downstream diff — generated files start showing up in
    ``git status`` for no reason and the contract becomes noise.
    """

    def test_typescript_is_byte_equal(self) -> None:
        a = emit_typescript(load_canvas_schemas())
        b = emit_typescript(load_canvas_schemas())
        assert a == b


class TestRegeneratePackages:
    """The CLI entry point writes to the forge repo's ``packages/`` tree.

    Use a tmp repo root so the test never touches the real worktree.
    """

    def test_writes_two_typescript_files(self, tmp_path: Path) -> None:
        written = regenerate_packages(repo_root=tmp_path)
        rels = {p.relative_to(tmp_path).as_posix() for p in written}
        assert rels == {
            "packages/canvas-vue/src/generated/props.ts",
            "packages/canvas-svelte/src/generated/props.ts",
        }

    def test_outputs_are_byte_stable(self, tmp_path: Path) -> None:
        regenerate_packages(repo_root=tmp_path)
        snapshot = {
            p: (tmp_path / p).read_bytes()
            for p in (
                "packages/canvas-vue/src/generated/props.ts",
                "packages/canvas-svelte/src/generated/props.ts",
            )
        }
        # Re-run — every file must be byte-identical.
        regenerate_packages(repo_root=tmp_path)
        for rel, expected in snapshot.items():
            assert (tmp_path / rel).read_bytes() == expected, f"{rel} changed across runs"

    def test_vue_and_svelte_emit_same_typescript(self, tmp_path: Path) -> None:
        # Both Vue and Svelte packages get the same TS module — they
        # share the schema source. If we ever diverge here, the canvas
        # contract is no longer single-source.
        regenerate_packages(repo_root=tmp_path)
        vue = (tmp_path / "packages/canvas-vue/src/generated/props.ts").read_text()
        svelte = (tmp_path / "packages/canvas-svelte/src/generated/props.ts").read_text()
        assert vue == svelte


class TestSchemaVersion:
    def test_schema_version_is_int(self) -> None:
        # The TODO at pipeline.py:216 anticipates wiring this through
        # provenance later. For now it just has to exist as an int so
        # generated files carry a stable, machine-readable tag.
        assert isinstance(SCHEMA_VERSION, int)
        assert SCHEMA_VERSION >= 1


class TestEmitterRejectsUnsupportedSchema:
    """Inherit the strict subset from ``forge.codegen.ui_protocol``."""

    def test_non_object_top_level_rejected(self, tmp_path: Path) -> None:
        from forge.errors import GeneratorError

        bad = tmp_path / "Bad.props.schema.json"
        bad.write_text(
            '{"title": "BadProps", "type": "array", "items": {"type": "string"}}'
        )
        schemas = load_canvas_schemas(tmp_path)
        with pytest.raises(GeneratorError, match="must be type=object"):
            emit_typescript(schemas)
