"""Tests for the canvas-lint codegen (Theme 1C).

Theme 1A pinned drift in the three hand-synced lint files via a
fingerprint test. Theme 1C — this module — generates all three files
from a single declarative description in
:mod:`forge.codegen.canvas_lint`. These tests assert:

    * the emitter is **byte-stable** across repeated runs (a flaky
      emitter would poison every generated diff)
    * the ``SCHEMA_VERSION`` tag is present in the banner of each
      generated language
    * every canonical ``TypeRule`` name lands in both TS and Dart
      output (a regression where someone deletes a branch fails here)
    * the emitter accepts an empty rule set and produces a still-valid
      no-op file (the empty case proves the loop scaffolding is sane)
    * the Vue and Svelte TS outputs are byte-identical (single source)
    * ``regenerate_packages`` writes exactly the three expected paths
"""

from __future__ import annotations

from pathlib import Path

from forge.codegen.canvas_lint import (
    SCHEMA_VERSION,
    TypeRule,
    _TYPE_RULES,
    emit_dart,
    emit_typescript,
    regenerate_packages,
)


# ---------------------------------------------------------------------------
# Canonical rule set
# ---------------------------------------------------------------------------


_EXPECTED_RULE_NAMES = {
    "string",
    "integer",
    "number",
    "boolean",
    "array",
    "object",
}


class TestCanonicalRuleSet:
    def test_every_json_schema_primitive_has_a_rule(self) -> None:
        # If the canonical set ever shrinks below this baseline, the
        # generated lint silently stops checking one of the JSON Schema
        # primitives — a contract regression we want to catch loudly.
        names = {r.name for r in _TYPE_RULES}
        assert names == _EXPECTED_RULE_NAMES, (
            f"rule-name drift: missing {_EXPECTED_RULE_NAMES - names!r}, "
            f"unexpected {names - _EXPECTED_RULE_NAMES!r}"
        )

    def test_rule_name_matches_json_type(self) -> None:
        # Sanity: the canonical name and the json_type keyword must
        # agree so the generated ``if (ty === '<json_type>')`` branch
        # actually fires for the rule named ``<name>``.
        for rule in _TYPE_RULES:
            assert rule.name == rule.json_type

    def test_every_message_uses_actual_placeholder(self) -> None:
        # The per-language emitters substitute ``{actual}`` with the
        # right runtime-type expression. A rule missing the placeholder
        # would silently emit a message without the actual-type info.
        for rule in _TYPE_RULES:
            assert "{actual}" in rule.message, (
                f"rule {rule.name!r} message missing {{actual}}: {rule.message!r}"
            )


# ---------------------------------------------------------------------------
# Banner / SCHEMA_VERSION
# ---------------------------------------------------------------------------


class TestBanners:
    def test_typescript_banner_carries_schema_version(self) -> None:
        body = emit_typescript()
        assert "AUTOGENERATED — DO NOT EDIT." in body
        assert f"Schema version: {SCHEMA_VERSION}" in body
        assert "forge/codegen/canvas_lint.py" in body

    def test_dart_banner_carries_schema_version(self) -> None:
        body = emit_dart()
        assert "AUTOGENERATED — DO NOT EDIT." in body
        assert f"Schema version: {SCHEMA_VERSION}" in body
        assert "forge/codegen/canvas_lint.py" in body

    def test_schema_version_is_int(self) -> None:
        assert isinstance(SCHEMA_VERSION, int)
        assert SCHEMA_VERSION >= 1


# ---------------------------------------------------------------------------
# Public API survives codegen
# ---------------------------------------------------------------------------


class TestPublicApi:
    """Generated files must export the same public API the canvas
    packages and consumers depend on (``lintProps``,
    ``warnOnLintIssues``, ``LintIssue``). Loss of any of these breaks
    every canvas consumer at build time.
    """

    def test_typescript_exports_lint_props(self) -> None:
        body = emit_typescript()
        assert "export function lintProps(" in body
        assert "export function warnOnLintIssues(" in body
        assert "export interface LintIssue {" in body

    def test_typescript_has_production_short_circuit(self) -> None:
        body = emit_typescript()
        # Both production-mode signals — Vite (``import.meta.env.PROD``)
        # and non-Vite (``process.env.NODE_ENV``) — must be present so
        # warnOnLintIssues is a no-op in prod builds.
        assert "import.meta" in body and "PROD" in body
        assert "process.env" in body and "NODE_ENV" in body

    def test_dart_exports_lint_props(self) -> None:
        body = emit_dart()
        assert "List<LintIssue> lintProps(" in body
        assert "void warnOnLintIssues(" in body
        assert "class LintIssue {" in body

    def test_dart_has_production_short_circuit(self) -> None:
        body = emit_dart()
        assert "kReleaseMode" in body
        assert "import 'package:flutter/foundation.dart';" in body


# ---------------------------------------------------------------------------
# Rule coverage in the generated output
# ---------------------------------------------------------------------------


class TestRuleCoverageInOutput:
    """Every ``TypeRule`` must produce a corresponding ``if`` branch in
    the generated source. The check is by-string presence of the
    ``ty === '<json_type>'`` (TS) and ``ty == '<json_type>'`` (Dart)
    discriminators — a rule whose branch silently vanished would not
    show up here.
    """

    def test_typescript_emits_every_rule(self) -> None:
        body = emit_typescript()
        for rule in _TYPE_RULES:
            assert f"ty === '{rule.json_type}'" in body, (
                f"TS output missing branch for rule {rule.name}"
            )
            # The mismatch expression itself must also land in the
            # generated source (a typo in the emitter that swapped one
            # rule's expression for another's would survive the
            # discriminator check above).
            assert rule.ts_mismatch in body

    def test_dart_emits_every_rule(self) -> None:
        body = emit_dart()
        for rule in _TYPE_RULES:
            assert f"ty == '{rule.json_type}'" in body, (
                f"Dart output missing branch for rule {rule.name}"
            )
            assert rule.dart_mismatch in body


# ---------------------------------------------------------------------------
# Empty rule set
# ---------------------------------------------------------------------------


class TestEmptyRuleSet:
    """Running the emitter against an empty rule list must produce a
    valid no-op file: the type-branch loop disappears, but every other
    structural piece (required loop, additional-properties guard, enum
    check, prod gate) survives. This proves the chain assembly isn't
    fragile to the rule list shrinking.
    """

    def test_typescript_empty_rules_still_valid(self) -> None:
        body = emit_typescript(rules=())
        # Structural pieces survive:
        assert "export function lintProps(" in body
        assert "required prop is missing" in body
        assert "unknown prop" in body
        assert "Enum check" in body
        # Type-check chain is absent:
        for rule in _TYPE_RULES:
            assert f"ty === '{rule.json_type}'" not in body

    def test_dart_empty_rules_still_valid(self) -> None:
        body = emit_dart(rules=())
        assert "List<LintIssue> lintProps(" in body
        assert "required prop is missing" in body
        assert "unknown prop" in body
        assert "Enum check" in body
        for rule in _TYPE_RULES:
            assert f"ty == '{rule.json_type}'" not in body


# ---------------------------------------------------------------------------
# Idempotency
# ---------------------------------------------------------------------------


class TestIdempotency:
    """Codegen MUST be byte-stable. Without this, every regeneration
    surfaces noise in ``git status`` and the contract becomes noise.
    """

    def test_typescript_emit_is_byte_equal_across_runs(self) -> None:
        assert emit_typescript() == emit_typescript()

    def test_dart_emit_is_byte_equal_across_runs(self) -> None:
        assert emit_dart() == emit_dart()

    def test_regenerate_packages_is_byte_stable(self, tmp_path: Path) -> None:
        regenerate_packages(repo_root=tmp_path)
        snapshot = {
            p: (tmp_path / p).read_bytes()
            for p in (
                "packages/canvas-vue/src/lint.ts",
                "packages/canvas-svelte/src/lint.ts",
                "packages/forge-canvas-dart/lib/src/lint.dart",
            )
        }
        regenerate_packages(repo_root=tmp_path)
        for rel, expected in snapshot.items():
            assert (tmp_path / rel).read_bytes() == expected, (
                f"{rel} changed across runs"
            )


# ---------------------------------------------------------------------------
# Vue/Svelte equivalence + regenerate_packages contract
# ---------------------------------------------------------------------------


class TestRegeneratePackages:
    def test_writes_every_target(self, tmp_path: Path) -> None:
        written = regenerate_packages(repo_root=tmp_path)
        rels = {p.relative_to(tmp_path).as_posix() for p in written}
        assert rels == {
            "packages/canvas-vue/src/lint.ts",
            "packages/canvas-svelte/src/lint.ts",
            "packages/forge-canvas-dart/lib/src/lint.dart",
        }

    def test_vue_and_svelte_emit_same_typescript(self, tmp_path: Path) -> None:
        # Both Vue and Svelte packages get the same TS module — they
        # share the lint source. Divergence here would silently break
        # the polyglot promise (the Svelte consumer would see a fix the
        # Vue consumer doesn't, or vice versa).
        regenerate_packages(repo_root=tmp_path)
        vue = (tmp_path / "packages/canvas-vue/src/lint.ts").read_text()
        svelte = (tmp_path / "packages/canvas-svelte/src/lint.ts").read_text()
        assert vue == svelte


# ---------------------------------------------------------------------------
# Custom-rule injection (exercises the dataclass contract)
# ---------------------------------------------------------------------------


class TestCustomRules:
    """The emitter accepts an arbitrary ``tuple[TypeRule, ...]`` —
    callers can in principle wire in a project-specific rule set
    (future hook). Smoke-test that path so the dataclass contract
    doesn't decay.
    """

    def test_custom_single_rule(self) -> None:
        custom = (
            TypeRule(
                name="binary",
                json_type="binary",
                ts_mismatch="!(value instanceof Uint8Array)",
                dart_mismatch="value is! List<int>",
                message="expected binary, got {actual}",
            ),
        )
        ts = emit_typescript(rules=custom)
        dart = emit_dart(rules=custom)
        # Custom rule lands in both languages:
        assert "ty === 'binary'" in ts
        assert "ty == 'binary'" in dart
        # Canonical rules are absent (we passed only the custom rule):
        assert "ty === 'string'" not in ts
        assert "ty == 'string'" not in dart
