"""Tests for the canvas-props schema codegen (Theme 1B).

The emitter is a thin wrapper over :mod:`forge.codegen.ui_protocol` — its
job is to:

    * load the right schema directory
      (``forge/templates/_shared/canvas-components/*.props.schema.json``)
    * stamp the right banner so generated files point at the canvas
      sources, not the ui-protocol ones
    * carry a ``schema_version`` tag that satisfies the
      ``pipeline.py:216`` TODO

These tests assert exactly those properties, plus byte-stable idempotency
(running the emitter twice produces the same bytes) — the load-bearing
invariant for codegen at large.

The module emits TypeScript, Dart, and Pydantic. The Pydantic output
is also exercised by ``tests/test_codegen_pipeline.py`` (which drives
the full ``run_codegen`` pipeline against a synthetic Python backend).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from forge.codegen.canvas_props import (
    DEFAULT_SCHEMA_ROOT,
    SCHEMA_VERSION,
    emit_dart,
    emit_pydantic,
    emit_typescript,
    load_canvas_schemas,
    regenerate_packages,
)

# Per-schema fields that must round-trip into every generated target. The
# tuples are ordered (schema_title, [required_field_names...]). Every
# field listed here must show up by string presence in TS / Dart / Py
# output — sufficient as a codegen contract test (a stronger test would
# parse the emitted source, which the existing ui_protocol tests already
# do at the helper level).
_EXPECTED_FIELDS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("CodeViewerProps", ("code", "language", "filename", "showLineNumbers")),
    ("DataTableProps", ("columns", "rows", "pageSize")),
    ("DynamicFormProps", ("title", "fields", "submitLabel", "cancelLabel")),
    ("ReportProps", ("title", "markdown")),
    ("WorkflowDiagramProps", ("nodes", "edges")),
)


class TestLoadCanvasSchemas:
    def test_loads_all_five_shipped_schemas(self) -> None:
        schemas = load_canvas_schemas()
        assert {s.title for s in schemas} == {
            "CodeViewerProps",
            "DataTableProps",
            "DynamicFormProps",
            "ReportProps",
            "WorkflowDiagramProps",
        }

    def test_default_root_points_at_canvas_components_dir(self) -> None:
        # Sanity: the constant must match where the schemas actually
        # live, or downstream emit code silently emits nothing.
        assert DEFAULT_SCHEMA_ROOT.is_dir()
        assert (DEFAULT_SCHEMA_ROOT / "DataTable.props.schema.json").is_file()


class TestEmitTypescript:
    def test_banner_is_autogenerated(self) -> None:
        out = emit_typescript(load_canvas_schemas())
        assert "AUTOGENERATED — DO NOT EDIT." in out
        assert "forge/templates/_shared/canvas-components" in out
        assert f"Schema version: {SCHEMA_VERSION}" in out

    def test_every_schema_emits_interface(self) -> None:
        out = emit_typescript(load_canvas_schemas())
        for title, _ in _EXPECTED_FIELDS:
            assert f"export interface {title}" in out, f"missing TS interface {title}"

    def test_every_field_appears(self) -> None:
        out = emit_typescript(load_canvas_schemas())
        for title, fields in _EXPECTED_FIELDS:
            for f in fields:
                assert f in out, f"TS output missing field {f} (from {title})"

    def test_enum_becomes_literal_union(self) -> None:
        # DynamicForm.fields[].type is enum: ["text", ..., "textarea"]
        out = emit_typescript(load_canvas_schemas())
        assert '"text" | "number" | "password"' in out


class TestEmitDart:
    def test_banner_is_autogenerated(self) -> None:
        out = emit_dart(load_canvas_schemas())
        assert "AUTOGENERATED — DO NOT EDIT." in out
        assert "forge/templates/_shared/canvas-components" in out
        assert f"Schema version: {SCHEMA_VERSION}" in out

    def test_every_schema_emits_class(self) -> None:
        out = emit_dart(load_canvas_schemas())
        for title, _ in _EXPECTED_FIELDS:
            # Initiative #8: every emitted class is `final` so a
            # downstream app cannot subclass the schema-derived shape
            # and silently invalidate it. The `final class` modifier
            # is Dart 3+.
            assert f"final class {title} {{" in out, f"missing Dart class {title}"

    def test_every_field_appears(self) -> None:
        out = emit_dart(load_canvas_schemas())
        for title, fields in _EXPECTED_FIELDS:
            for f in fields:
                assert f in out, f"Dart output missing field {f} (from {title})"

    def test_factory_constructors_present(self) -> None:
        out = emit_dart(load_canvas_schemas())
        for title, _ in _EXPECTED_FIELDS:
            assert f"factory {title}.fromJson" in out

    def test_required_fields_marked_required(self) -> None:
        # CodeViewerProps requires (code, language); both must carry
        # ``required this.<field>`` in the const ctor.
        out = emit_dart(load_canvas_schemas())
        assert "required this.code" in out
        assert "required this.language" in out

    def test_optional_fields_nullable(self) -> None:
        # CodeViewerProps.filename is optional → ``String?``.
        out = emit_dart(load_canvas_schemas())
        assert "final String? filename" in out


class TestDartNestedSealedClasses:
    """Initiative #8: typed inner classes for nested array-of-object fields.

    Pre-#8 the Dart emitter collapsed every ``items: {type: object}`` to
    ``List<Map<String, dynamic>>`` — typing was lost the moment props
    crossed the codegen boundary, and every consumer (``data_table.dart``,
    ``dynamic_form.dart``, ``workflow_diagram.dart``) had to hand-roll
    its own ``_Column`` / ``_Field`` / ``_WfNode`` mirror class.

    Initiative #8 lifts the schema's nested shape into the emitted file
    as a sealed inner class so a single source of truth covers every
    nested level.

    Naming rule (matches :func:`_nested_class_name`): strip the trailing
    ``Props`` from the parent title, append a singularised PascalCase
    field name. ``DynamicFormProps.fields`` → ``DynamicFormField``;
    ``WorkflowDiagramProps.nodes`` → ``WorkflowDiagramNode``.
    """

    def test_dynamic_form_fields_becomes_typed_list(self) -> None:
        out = emit_dart(load_canvas_schemas())
        assert "final class DynamicFormField {" in out
        assert "final List<DynamicFormField> fields;" in out
        # `Map<String, dynamic>` must NOT appear on the parent's
        # `fields` field declaration any more.
        assert "final List<Map<String, dynamic>> fields;" not in out

    def test_dynamic_form_field_has_typed_properties(self) -> None:
        out = emit_dart(load_canvas_schemas())
        # All schema-declared properties on the nested item must show
        # up as typed fields on the inner class.
        # `name`, `label` are required strings.
        # `type` is a string enum → emitted as `String`.
        # `required` is optional bool.
        # `default` is a wildcard `{}` → emitted as `dynamic` (no `?`
        # marker because `dynamic` is implicitly nullable).
        # `options` is optional `List<String>`.
        # `description` is optional string.
        for expected in (
            "final String name;",
            "final String label;",
            "final String type;",
            "final bool? required;",
            "final dynamic defaultValue;",
            "final List<String>? options;",
            "final String? description;",
        ):
            assert expected in out, f"DynamicFormField missing field decl: {expected!r}"

    def test_dynamic_form_field_reserved_word_remapped(self) -> None:
        # ``default`` is a Dart reserved word — the emitter must rename
        # the field on the Dart side while keeping the original JSON key.
        out = emit_dart(load_canvas_schemas())
        assert "this.defaultValue" in out
        # The JSON key must stay ``'default'`` so wire compatibility
        # with the Pydantic / TS side is preserved.
        assert "defaultValue: json['default']" in out
        assert "'default': defaultValue" in out

    def test_data_table_columns_becomes_typed_list(self) -> None:
        out = emit_dart(load_canvas_schemas())
        assert "final class DataTableColumn {" in out
        assert "final List<DataTableColumn> columns;" in out
        # Inner class typed fields.
        assert "final String key;" in out
        assert "final String label;" in out
        assert "final bool? sortable;" in out

    def test_data_table_rows_stays_loose_map(self) -> None:
        # DataTable.rows.items has `additionalProperties: true` and no
        # `properties` — there is no fixed shape to type against, so
        # the emitter must NOT invent a class. `List<Map<String,
        # dynamic>>` is the correct ceiling here.
        out = emit_dart(load_canvas_schemas())
        assert "final List<Map<String, dynamic>> rows;" in out
        # Sanity: no ``DataTableRow`` class was synthesised.
        assert "class DataTableRow {" not in out

    def test_workflow_diagram_nodes_and_edges_typed(self) -> None:
        out = emit_dart(load_canvas_schemas())
        assert "final class WorkflowDiagramNode {" in out
        assert "final class WorkflowDiagramEdge {" in out
        assert "final List<WorkflowDiagramNode> nodes;" in out
        assert "final List<WorkflowDiagramEdge> edges;" in out
        # `from` is not a reserved word but a built-in identifier; the
        # emitter passes it through verbatim.
        assert "final String from;" in out
        assert "final String to;" in out

    def test_nested_class_factory_constructors_present(self) -> None:
        out = emit_dart(load_canvas_schemas())
        for nested in (
            "DataTableColumn",
            "DynamicFormField",
            "WorkflowDiagramNode",
            "WorkflowDiagramEdge",
        ):
            assert f"factory {nested}.fromJson" in out, f"missing {nested}.fromJson"
            assert "Map<String, dynamic> toJson()" in out  # at least one to_json

    def test_parent_from_json_constructs_inner_via_factory(self) -> None:
        # The recurse-into-typed-items branch should call the inner
        # class's `.fromJson` for every list element, not just cast.
        out = emit_dart(load_canvas_schemas())
        assert "DynamicFormField.fromJson" in out
        assert "DataTableColumn.fromJson" in out
        assert "WorkflowDiagramNode.fromJson" in out
        assert "WorkflowDiagramEdge.fromJson" in out

    def test_typed_array_parse_is_strict(self) -> None:
        # The typed-array parse path must NOT silently drop
        # non-conforming elements. Codex review flagged
        # `.whereType<Map>()` as data-loss for known schema shapes;
        # the strict-cast replacement (`e as Map`) raises a TypeError
        # on non-Map elements so misshapen payloads fail loud.
        out = emit_dart(load_canvas_schemas())
        assert ".whereType<Map>()" not in out, (
            "typed-array parse uses .whereType which silently drops "
            "malformed elements; use a strict `as Map` cast so "
            "known-shape violations raise"
        )
        # Sanity: the strict-cast form is present.
        assert ".map((e) => DynamicFormField.fromJson(" in out
        assert "e as Map" in out

    def test_parent_to_json_serialises_inner_via_to_json(self) -> None:
        # Symmetric direction: `toJson` for the parent must map each
        # inner element through its own `toJson()` so the wire format
        # round-trips identically to the input.
        out = emit_dart(load_canvas_schemas())
        assert "fields.map((e) => e.toJson()).toList()" in out
        assert "columns.map((e) => e.toJson()).toList()" in out
        assert "nodes.map((e) => e.toJson()).toList()" in out
        assert "edges.map((e) => e.toJson()).toList()" in out

    def test_inner_classes_emitted_before_parent(self) -> None:
        # Dart compiles top-to-bottom; a class reference resolves
        # symbol-table-wide so order does not strictly matter, but
        # putting the inner class first reads naturally. Lock the
        # ordering with an indexOf check so a refactor that flips it
        # is intentional, not accidental.
        out = emit_dart(load_canvas_schemas())
        assert out.index("final class DynamicFormField {") < out.index(
            "final class DynamicFormProps {"
        )
        assert out.index("final class DataTableColumn {") < out.index(
            "final class DataTableProps {"
        )
        assert out.index("final class WorkflowDiagramNode {") < out.index(
            "final class WorkflowDiagramProps {"
        )
        assert out.index("final class WorkflowDiagramEdge {") < out.index(
            "final class WorkflowDiagramProps {"
        )


class TestEmitPydantic:
    def test_banner_is_autogenerated(self) -> None:
        out = emit_pydantic(load_canvas_schemas())
        assert "AUTOGENERATED — DO NOT EDIT." in out
        assert "forge/templates/_shared/canvas-components" in out
        assert f"Schema version: {SCHEMA_VERSION}" in out

    def test_every_schema_emits_basemodel(self) -> None:
        out = emit_pydantic(load_canvas_schemas())
        for title, _ in _EXPECTED_FIELDS:
            assert f"class {title}(BaseModel):" in out, f"missing Pydantic class {title}"

    def test_every_field_appears(self) -> None:
        out = emit_pydantic(load_canvas_schemas())
        for title, fields in _EXPECTED_FIELDS:
            for f in fields:
                assert f in out, f"Pydantic output missing field {f} (from {title})"

    def test_imports_present(self) -> None:
        # The generated module must compile standalone — required
        # imports (`BaseModel`, `Field`, `Literal`, `Any`, `ConfigDict`)
        # all live in the banner.
        out = emit_pydantic(load_canvas_schemas())
        assert "from pydantic import BaseModel, ConfigDict, Field" in out
        assert "from typing import Any, Literal" in out

    def test_required_vs_optional(self) -> None:
        # CodeViewerProps.code is required → plain ``code: str``
        # CodeViewerProps.filename is optional → ``filename: str | None = None``
        out = emit_pydantic(load_canvas_schemas())
        assert "code: str\n" in out
        assert "filename: str | None = None" in out

    def test_nested_arrays_render_as_list_of_dict(self) -> None:
        # The Pydantic emitter (inherited from forge.codegen.ui_protocol)
        # does NOT recurse into ``items: {type: object}`` — it collapses
        # the inner object to ``dict[str, Any]``. This matches how
        # ui_protocol.py renders nested AG-UI payload shapes today. If
        # someone teaches the helper to recurse, enums inside array
        # items would land as a Literal — until then, this test
        # documents the conscious behaviour.
        out = emit_pydantic(load_canvas_schemas())
        assert "nodes: list[dict[str, Any]]" in out
        assert "edges: list[dict[str, Any]]" in out


class TestIdempotency:
    """Codegen MUST be byte-stable across runs.

    A flaky emitter (dict iteration order leaking, timestamps, anything)
    poisons every downstream diff — generated files start showing up in
    ``git status`` for no reason and the contract becomes noise.
    """

    def test_typescript_is_byte_equal(self) -> None:
        a = emit_typescript(load_canvas_schemas())
        b = emit_typescript(load_canvas_schemas())
        assert a == b

    def test_dart_is_byte_equal(self) -> None:
        a = emit_dart(load_canvas_schemas())
        b = emit_dart(load_canvas_schemas())
        assert a == b

    def test_pydantic_is_byte_equal(self) -> None:
        a = emit_pydantic(load_canvas_schemas())
        b = emit_pydantic(load_canvas_schemas())
        assert a == b


class TestRegeneratePackages:
    """The CLI entry point writes to the forge repo's ``packages/`` tree.

    Use a tmp repo root so the test never touches the real worktree.
    """

    def test_writes_every_target(self, tmp_path: Path) -> None:
        written = regenerate_packages(repo_root=tmp_path)
        rels = {p.relative_to(tmp_path).as_posix() for p in written}
        assert rels == {
            "packages/canvas-vue/src/generated/props.ts",
            "packages/canvas-svelte/src/generated/props.ts",
            "packages/forge-canvas-dart/lib/src/generated/props.dart",
        }

    def test_outputs_are_byte_stable(self, tmp_path: Path) -> None:
        regenerate_packages(repo_root=tmp_path)
        snapshot = {
            p: (tmp_path / p).read_bytes()
            for p in (
                "packages/canvas-vue/src/generated/props.ts",
                "packages/canvas-svelte/src/generated/props.ts",
                "packages/forge-canvas-dart/lib/src/generated/props.dart",
            )
        }
        # Re-run — every file must be byte-identical.
        regenerate_packages(repo_root=tmp_path)
        for rel, expected in snapshot.items():
            assert (tmp_path / rel).read_bytes() == expected, f"{rel} changed across runs"

    def test_vue_and_svelte_emit_same_typescript(self, tmp_path: Path) -> None:
        # Both Vue and Svelte packages get the same TS module — they
        # share the schema source. If we ever diverge here, the canvas
        # contract is no longer single-source.
        regenerate_packages(repo_root=tmp_path)
        vue = (tmp_path / "packages/canvas-vue/src/generated/props.ts").read_text()
        svelte = (tmp_path / "packages/canvas-svelte/src/generated/props.ts").read_text()
        assert vue == svelte


class TestSchemaVersion:
    def test_schema_version_is_int(self) -> None:
        # The TODO at pipeline.py:216 anticipates wiring this through
        # provenance later. For now it just has to exist as an int so
        # generated files carry a stable, machine-readable tag.
        assert isinstance(SCHEMA_VERSION, int)
        assert SCHEMA_VERSION >= 1


class TestEmitterRejectsUnsupportedSchema:
    """Inherit the strict subset from ``forge.codegen.ui_protocol``."""

    def test_non_object_top_level_rejected(self, tmp_path: Path) -> None:
        from forge.errors import GeneratorError

        bad = tmp_path / "Bad.props.schema.json"
        bad.write_text(
            '{"title": "BadProps", "type": "array", "items": {"type": "string"}}'
        )
        schemas = load_canvas_schemas(tmp_path)
        with pytest.raises(GeneratorError, match="must be type=object"):
            emit_typescript(schemas)
