"""Sample connector — read-only synthetic-records source.

Deliberately bare-bones: every read produces ``record_count``
deterministic records with a fixed shape so demos, smoke tests, and the
sync runner's source → mapping → destination loop can be exercised
without provisioning a real external system.

Records are generated in-process; there is no remote system to contact,
no secrets to fetch.

Vendored, self-contained: imports only the stdlib + pydantic.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field

from app.connectors.base import (
    Connector,
    ConnectorPage,
)


class SampleConfig(BaseModel):
    """Config for the ``sample`` connector.

    ``record_count`` controls how many synthetic records the connector
    emits per full read; ``batch_size`` controls how many it yields per
    ``ConnectorPage`` so the runner's retry-resume cursor flips at a
    realistic cadence.
    """

    record_count: int = Field(
        default=100,
        ge=0,
        description=(
            "Total synthetic records to emit per full read. ``0`` is "
            "legal (a no-op read) so test setups can assert empty-source "
            "paths without special-casing."
        ),
    )
    batch_size: int = Field(
        default=50,
        ge=1,
        le=10_000,
        description="Records per ``ConnectorPage`` yield.",
    )


_RECORDS_EPOCH = datetime(2026, 1, 1, tzinfo=UTC)


def _build_record(index: int) -> dict[str, Any]:
    """Deterministically build the synthetic record at ``index``.

    Stable across processes / restarts so retry-resume cursors and
    downstream idempotency keys behave the way they would against a real
    source. Shape is fixed (``id``, ``title``, ``body``, ``created_at``)
    so a default mapping can rely on these keys being present.
    """
    return {
        "id": f"sample-{index:03d}",
        "title": f"Sample record {index}",
        "body": (
            "Synthetic record generated by the sample connector. Use this "
            "dataset to exercise mapping and downstream steps end-to-end "
            "without a real source."
        ),
        # Spread the timestamps one second apart so any
        # ordering-by-created_at assertion still surfaces ordering bugs.
        "created_at": _RECORDS_EPOCH.replace(second=index % 60).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }


class SampleConnector(Connector):
    """Generates synthetic records in-process. Read-only."""

    name = "sample"
    display_name = "Sample data"
    capabilities = "read"
    ConfigModel = SampleConfig
    SecretsModel = None

    def __repr__(self) -> str:  # pragma: no cover — trivial
        return f"SampleConnector(record_count={self.cfg.record_count})"

    @property
    def cfg(self) -> SampleConfig:
        return self._config  # type: ignore[return-value]

    async def iter_records(
        self,
        cursor: dict[str, Any] | None = None,
    ) -> AsyncIterator[ConnectorPage]:
        total = self.cfg.record_count
        batch = self.cfg.batch_size
        offset = int((cursor or {}).get("offset", 0))

        # Edge: ``record_count=0`` — still yield one ``done`` page so the
        # runner's outer loop terminates cleanly without special-casing.
        if total <= 0:
            yield ConnectorPage(records=[], cursor=None, done=True)
            return

        while offset < total:
            end = min(offset + batch, total)
            records = [_build_record(i) for i in range(offset, end)]
            done = end >= total
            # Cursor on the final page is ``None``; on intermediate pages
            # an offset cursor lets a retry resume at the same boundary.
            next_cursor: dict[str, Any] | None = None if done else {"offset": end}
            yield ConnectorPage(records=records, cursor=next_cursor, done=done)
            offset = end
