"""Read and write the project-root ``forge.toml`` manifest.

``forge.toml`` is the source of truth for ``forge update``: it records
which forge version generated the project, where the templates live, and
the full feature state (enabled flag + options dict per feature).

Format:

    [forge]
    version = "0.2.0"
    project_name = "acme"

    [forge.templates]
    python = "services/python-service-template"
    vue    = "apps/vue-frontend-template"

    [forge.features.rate_limit]
    enabled = true
    options = {}

    [forge.features.rag_pipeline]
    enabled = true
    options = { vector_store = "pgvector" }

Older forge versions emitted a flat ``[forge.features] enabled = [keys]``
list without options. The reader accepts that shape too (with a
deprecation warning) so existing projects can run ``forge update``
without manual migration; the writer always emits the per-key table form.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import tomlkit

logger = logging.getLogger(__name__)


@dataclass
class ForgeTomlData:
    """Parsed ``forge.toml`` contents."""

    version: str
    project_name: str
    templates: dict[str, str] = field(default_factory=dict)
    features: dict[str, dict[str, Any]] = field(default_factory=dict)
    # When True, the file was loaded from the legacy flat-list feature shape
    # and needs a writer pass to upgrade. ``forge update`` should set this as
    # a migration signal.
    legacy_features_format: bool = False


def read_forge_toml(path: Path) -> ForgeTomlData:
    """Parse ``forge.toml`` into a structured object.

    Raises ``FileNotFoundError`` if the file is missing and ``ValueError``
    on malformed content. Missing sections default to empty dicts.
    """
    if not path.is_file():
        raise FileNotFoundError(f"forge.toml not found at {path}")
    doc = tomlkit.parse(path.read_text(encoding="utf-8"))

    forge = doc.get("forge")
    if forge is None:
        raise ValueError(f"{path}: missing [forge] section")

    version = str(forge.get("version", "0.0.0+unknown"))
    project_name = str(forge.get("project_name", ""))

    templates_tbl = forge.get("templates") or {}
    templates: dict[str, str] = {k: str(v) for k, v in dict(templates_tbl).items()}

    features_tbl = forge.get("features") or {}
    features: dict[str, dict[str, Any]] = {}
    legacy = False

    # Legacy shape: [forge.features] with `enabled = [...]` list of keys.
    if "enabled" in features_tbl and isinstance(features_tbl["enabled"], list):
        legacy = True
        logger.warning(
            "%s: legacy [forge.features] flat-list shape detected; "
            "options will be lost. Re-run forge update to upgrade the file.",
            path,
        )
        for key in features_tbl["enabled"]:
            features[str(key)] = {"enabled": True, "options": {}}
    else:
        # New shape: each feature is its own sub-table
        # ``[forge.features.<key>]`` with ``enabled`` + ``options``.
        for key, sub in dict(features_tbl).items():
            if not isinstance(sub, dict):
                # A scalar under [forge.features] is malformed; skip with a warning.
                logger.warning(
                    "%s: [forge.features.%s] expected a table, got %s; ignored.",
                    path,
                    key,
                    type(sub).__name__,
                )
                continue
            enabled = bool(sub.get("enabled", False))
            options_raw = sub.get("options", {})
            options: dict[str, Any] = dict(options_raw) if isinstance(options_raw, dict) else {}
            features[str(key)] = {"enabled": enabled, "options": options}

    return ForgeTomlData(
        version=version,
        project_name=project_name,
        templates=templates,
        features=features,
        legacy_features_format=legacy,
    )


def write_forge_toml(
    path: Path,
    *,
    version: str,
    project_name: str,
    templates: dict[str, str],
    features: dict[str, dict[str, Any]],
) -> None:
    """Emit ``forge.toml`` in the canonical (non-legacy) shape."""
    doc = tomlkit.document()
    doc.add(tomlkit.comment("Generated by forge — do not edit by hand."))
    doc.add(
        tomlkit.comment(
            "Re-render any subdirectory with `copier update` using its `.copier-answers.yml`."
        )
    )

    forge_tbl = tomlkit.table()
    forge_tbl.add("version", version)
    forge_tbl.add("project_name", project_name)

    tpl_tbl = tomlkit.table()
    for key in sorted(templates):
        tpl_tbl.add(key, templates[key])
    forge_tbl.add("templates", tpl_tbl)

    features_tbl = tomlkit.table()
    for key in sorted(features):
        spec = features[key]
        sub = tomlkit.table()
        sub.add("enabled", bool(spec.get("enabled", False)))
        opts = spec.get("options", {}) or {}
        inline_opts = tomlkit.inline_table()
        for opt_key in sorted(opts):
            inline_opts[opt_key] = opts[opt_key]
        sub.add("options", inline_opts)
        features_tbl.add(key, sub)
    forge_tbl.add("features", features_tbl)

    doc.add("forge", forge_tbl)
    path.write_text(tomlkit.dumps(doc), encoding="utf-8")
