<script setup lang="ts">
// Layer-1 data-bound component generated by Forge (component_EntityList).
// Imports its contract types so a contract change is caught by vue-tsc (§D).
import type { EntityListListOutput } from '@/shared/api/EntityList.contract'

defineProps<{
  data: EntityListListOutput
}>()
</script>

<template>
  <ul class="entity-list divide-y">
    <li v-for="(item, index) in data.items" :key="index" class="py-2">
      {{ item }}
    </li>
  </ul>
</template>
