"""Generate MCP tools from the service's own OpenAPI spec.

Run via ``mise run mcp:codegen`` (or ``python -m app.mcp.codegen``); the
output is committed alongside the source so plugins consume
``tools.generated.py`` without a runtime dependency on the spec.
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

from weld.mcp_template.openapi import AuthConfig, openapi_to_tools


async def main(spec_path: Path, out_path: Path) -> None:
    spec = json.loads(spec_path.read_text())
    tools = openapi_to_tools(spec, auth=AuthConfig(kind="bearer"))
    out_path.write_text(
        "# Auto-generated by app.mcp.codegen — do not edit by hand.\n"
        f"TOOLS = {tools!r}\n"
    )


if __name__ == "__main__":
    spec = Path(sys.argv[1])
    out = Path(sys.argv[2])
    asyncio.run(main(spec, out))
