"""Generate MCP tools from the service's own OpenAPI spec.

Run via ``mise run mcp:codegen`` (or ``python -m app.mcp.codegen``). The
output is committed alongside the source so plugins consume the generated
tool list without a runtime dependency on the spec.

Uses the vendored OpenAPI → tools generator under
:mod:`app.mcp._template.openapi` — weld-free.
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

from app.mcp._template.openapi import AuthConfig, openapi_to_tools


async def main(spec_path: Path, out_path: Path) -> None:
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    tools = await openapi_to_tools(spec=spec, auth_config=AuthConfig(type="bearer"))
    tool_names = [t.name for t in tools]
    out_path.write_text(
        "# Auto-generated by app.mcp.codegen — do not edit by hand.\n"
        f"GENERATED_TOOL_NAMES = {tool_names!r}\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    spec = Path(sys.argv[1])
    out = Path(sys.argv[2])
    asyncio.run(main(spec, out))
