"""OpenAPI → MCP tools generator (vendored, self-contained).

For SaaS integrations with a published OpenAPI spec, a plugin can
auto-generate its tools instead of hand-writing a ``ToolDef`` per
endpoint::

    from app.mcp._template.openapi import AuthConfig, openapi_to_tools

    tools = await openapi_to_tools(
        spec_url="https://api.example.com/openapi.yaml",
        operations=["listThings", "getThing"],
        base_url="https://{subdomain}.example.com",
        auth_config=AuthConfig(type="bearer", credential_field="api_key"),
    )

The generator supports ``parameters`` (query/path/header) and JSON
``requestBody``. Multipart uploads / file downloads are out of scope.

Vendored, self-contained: imports the stdlib + httpx + PyYAML (the
``[openapi]`` extra ships PyYAML). No private SDKs.
"""

from __future__ import annotations

import json
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from string import Template
from typing import Any, Literal
from urllib.parse import quote

import httpx
import yaml

from app.mcp._template.errors import UpstreamError
from app.mcp._template.plugin import PluginContext, ToolDef

AuthType = Literal["none", "bearer", "basic", "apikey_header", "apikey_query"]


@dataclass
class AuthConfig:
    """How requests generated by :func:`openapi_to_tools` authenticate.

    ``credential_field`` (and ``credential_field_secondary`` for basic)
    name the keys in ``PluginContext.credentials`` the handler looks up at
    call time. Missing credentials raise :class:`UpstreamError`.
    """

    type: AuthType = "none"
    credential_field: str = "api_key"
    credential_field_secondary: str = "password"
    header_name: str = "Authorization"
    query_name: str = "api_key"

    @classmethod
    def from_openapi(cls, spec: dict) -> "AuthConfig":
        """Pick a primary security scheme from a spec's components block.

        Resolution order (first match wins): HTTP bearer → HTTP basic →
        apiKey header → apiKey query → none. OAuth2 / OpenID are returned
        as ``"none"`` — the host plugin must populate an access token and
        use a bearer config.
        """
        schemes = (spec.get("components") or {}).get("securitySchemes") or {}
        for _name, scheme in schemes.items():
            if not isinstance(scheme, dict):
                continue
            stype = (scheme.get("type") or "").lower()
            if stype == "http":
                http_scheme = (scheme.get("scheme") or "").lower()
                if http_scheme == "bearer":
                    return cls(type="bearer")
                if http_scheme == "basic":
                    return cls(type="basic")
            if stype == "apikey":
                location = (scheme.get("in") or "").lower()
                if location == "header":
                    return cls(
                        type="apikey_header",
                        header_name=scheme.get("name") or "X-API-Key",
                    )
                if location == "query":
                    return cls(
                        type="apikey_query",
                        query_name=scheme.get("name") or "api_key",
                    )
        return cls(type="none")


async def _fetch_spec(spec_url: str) -> dict:
    """Fetch an OpenAPI spec (JSON or YAML) from a URL."""
    async with httpx.AsyncClient(timeout=15.0) as client:
        resp = await client.get(spec_url)
        resp.raise_for_status()
    text = resp.text
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return yaml.safe_load(text)


def _load_spec(source: dict | str) -> dict:
    if isinstance(source, dict):
        return source
    return yaml.safe_load(source)


def _sanitise_name(op_id: str) -> str:
    """OpenAPI operationIds can contain dots/hyphens; MCP tool names can't."""
    return "".join(c if c.isalnum() or c == "_" else "_" for c in op_id)


def _resolve_ref(spec: dict, ref: str) -> dict:
    if not ref.startswith("#/"):
        return {}
    node: Any = spec
    for piece in ref[2:].split("/"):
        node = node.get(piece, {})
    return node if isinstance(node, dict) else {}


def _build_input_schema(op: dict, spec: dict) -> dict:
    """Derive a JSON schema from an OpenAPI operation."""
    props: dict[str, Any] = {}
    required: list[str] = []
    for param in op.get("parameters", []) or []:
        p = param
        if "$ref" in p:
            p = _resolve_ref(spec, p["$ref"])
        schema = p.get("schema") or {"type": "string"}
        name = p["name"]
        description = p.get("description", "")
        props[name] = {**schema, "description": description}
        if p.get("required"):
            required.append(name)
    body = op.get("requestBody", {})
    content = body.get("content", {}) if body else {}
    json_body = content.get("application/json", {})
    if json_body:
        body_schema = json_body.get("schema", {})
        if "$ref" in body_schema:
            body_schema = _resolve_ref(spec, body_schema["$ref"])
        props["body"] = {
            **body_schema,
            "description": body.get("description", "Request body"),
        }
        if body.get("required"):
            required.append("body")
    return {
        "type": "object",
        "properties": props,
        "required": required,
    }


def _render_path(path_template: str, args: dict) -> str:
    """Substitute ``{param}`` placeholders from args into the path."""
    out = path_template
    for key, value in list(args.items()):
        placeholder = "{" + key + "}"
        if placeholder in out:
            # Percent-encode the value (safe="") so a value containing path
            # delimiters (``/ ? #`` etc.) can't inject extra segments or a
            # query/fragment into the generated request URL.
            out = out.replace(placeholder, quote(str(value), safe=""))
            args.pop(key)
    return out


AuthHeaderFn = Callable[[PluginContext], tuple[str, str]]
"""``(ctx) -> (username, password)`` for HTTP basic auth. Return
``("Bearer <token>", "")`` to emit an Authorization header.
"""


async def openapi_to_tools(
    *,
    spec: dict | str | None = None,
    spec_url: str | None = None,
    operations: list[str] | None = None,
    base_url: str | None = None,
    auth: AuthHeaderFn | None = None,
    auth_config: AuthConfig | None = None,
    overrides: dict[str, Callable[[dict, PluginContext], Awaitable[Any]]] | None = None,
) -> list[ToolDef]:
    """Generate a :class:`ToolDef` list from an OpenAPI spec.

    Exactly one of ``spec`` (dict/str) or ``spec_url`` must be set.

    ``operations`` — when provided, only include operations whose
    ``operationId`` is in the list.

    ``base_url`` — override the server URL. May contain ``{field}`` tokens
    resolved from the caller's credentials at tool-call time.

    ``auth_config`` — declarative auth (bearer/basic/apikey). When omitted
    and ``auth`` is also None, falls back to :meth:`AuthConfig.from_openapi`.

    ``overrides`` — replace the auto-generated handler for specific
    operation IDs with hand-written coroutines.
    """
    if spec_url is not None:
        data = await _fetch_spec(spec_url)
    elif spec is not None:
        data = _load_spec(spec)
    else:
        raise ValueError("one of spec or spec_url is required")

    selected: set[str] | None = set(operations) if operations else None
    resolved_base = base_url or (data.get("servers") or [{}])[0].get("url", "")

    resolved_auth = auth_config
    if resolved_auth is None and auth is None:
        resolved_auth = AuthConfig.from_openapi(data)

    tools: list[ToolDef] = []
    for path, path_item in (data.get("paths") or {}).items():
        for method, op in path_item.items():
            if method.lower() not in {"get", "post", "put", "patch", "delete"}:
                continue
            if not isinstance(op, dict):
                continue
            op_id = op.get("operationId")
            if not op_id:
                continue
            if selected is not None and op_id not in selected:
                continue
            input_schema = _build_input_schema(op, data)
            tool_name = _sanitise_name(op_id)
            handler = (overrides or {}).get(op_id) or _make_handler(
                method=method.upper(),
                path=path,
                base_url=resolved_base,
                auth=auth,
                auth_config=resolved_auth,
            )
            tools.append(
                ToolDef(
                    name=tool_name,
                    description=op.get("summary") or op.get("description") or tool_name,
                    input_schema=input_schema,
                    handler=handler,
                )
            )
    return tools


def _require_cred(ctx: PluginContext, key: str) -> str:
    value = ctx.credentials.get(key)
    if not value:
        raise UpstreamError(f"integration is missing required credential {key!r}")
    return str(value)


def _apply_auth(
    *,
    auth_config: AuthConfig | None,
    auth: AuthHeaderFn | None,
    ctx: PluginContext,
    headers: dict[str, str],
    params: dict[str, Any],
) -> tuple[str, str] | None:
    """Mutate ``headers``/``params`` with auth material; return basic-auth tuple if applicable."""
    if auth_config is not None:
        t = auth_config.type
        if t == "none":
            return None
        if t == "bearer":
            token = _require_cred(ctx, auth_config.credential_field)
            headers[auth_config.header_name or "Authorization"] = f"Bearer {token}"
            return None
        if t == "basic":
            user = _require_cred(ctx, auth_config.credential_field)
            password = ctx.credentials.get(auth_config.credential_field_secondary, "")
            return (user, str(password))
        if t == "apikey_header":
            value = _require_cred(ctx, auth_config.credential_field)
            headers[auth_config.header_name] = value
            return None
        if t == "apikey_query":
            params[auth_config.query_name] = _require_cred(ctx, auth_config.credential_field)
            return None
    if auth is not None:
        u, p = auth(ctx)
        if u.startswith("Bearer ") and p == "":
            headers["Authorization"] = u
            return None
        return (u, p)
    return None


def _make_handler(
    *,
    method: str,
    path: str,
    base_url: str,
    auth: AuthHeaderFn | None,
    auth_config: AuthConfig | None = None,
) -> Callable[[dict, PluginContext], Awaitable[Any]]:
    async def handler(args: dict, ctx: PluginContext) -> Any:
        rendered_base = Template(base_url).safe_substitute(ctx.credentials)
        mutable_args = dict(args or {})
        body = mutable_args.pop("body", None)
        rendered_path = _render_path(path, mutable_args)
        url = rendered_base.rstrip("/") + rendered_path

        headers = {"Accept": "application/json"}
        auth_tuple = _apply_auth(
            auth_config=auth_config,
            auth=auth,
            ctx=ctx,
            headers=headers,
            params=mutable_args,
        )

        kwargs: dict[str, Any] = {"params": mutable_args, "headers": headers}
        if auth_tuple:
            kwargs["auth"] = auth_tuple
        if body is not None and method in {"POST", "PUT", "PATCH"}:
            kwargs["json"] = body

        resp = await ctx.http.request(method, url, **kwargs)
        if resp.status_code >= 400:
            raise UpstreamError(
                f"{method} {url} -> {resp.status_code}: {resp.text[:500]}",
                status_code=resp.status_code,
            )
        if not resp.content:
            return {"status": resp.status_code}
        try:
            return resp.json()
        except json.JSONDecodeError:
            return {"status": resp.status_code, "body": resp.text}

    return handler
