include: package:flutter_lints/flutter.yaml

plugins:
  riverpod_lint: ^3.1.9

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/src/api/generated/**"

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    prefer_final_locals: true
    sort_constructors_first: true
    unawaited_futures: true
    prefer_single_quotes: true
    require_trailing_commas: true
