"""Generate TypeScript / Dart / Pydantic types for **canvas component props**.

The canonical schemas live in
``forge/templates/_shared/canvas-components/*.props.schema.json``. This
module emits the three target languages canvas consumers care about.

Targets:

    * ``packages/canvas-vue/src/generated/props.ts`` (forge repo)
    * ``packages/canvas-svelte/src/generated/props.ts`` (forge repo)
    * ``packages/forge-canvas-dart/lib/src/generated/props.dart``
      (forge repo)
    * ``services/<name>/src/app/domain/canvas_props.py`` (emitted into
      every generated Python backend by
      :mod:`forge.codegen.pipeline`)

The TS / Pydantic emitters delegate to :mod:`forge.codegen.ui_protocol`;
the Dart emitter is canvas-specific because it walks nested
array-of-object properties and emits a typed sealed inner class per
nested schema (e.g. ``DynamicFormProps.fields`` becomes
``List<DynamicFormField>`` where ``DynamicFormField`` is a generated
sealed class). The ui-protocol Dart emitter collapses the same shape
to ``List<Map<String, dynamic>>``; canvas components rely on
typed nested access at the component layer so we lift the recursion
here.

Run as a script (``python -m forge.codegen.canvas_props``) to regenerate
the files inside the forge repo. The per-project Pydantic file is
written by the codegen pipeline on every ``forge new``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from forge.codegen.ui_protocol import (
    Schema,
    _pydantic_for_schema,
    _to_camel_case,
    _ts_for_schema,
    load_all,
)
from forge.errors import GeneratorError

# Bump when the canvas schema-set grows a breaking change. Mirrors the
# ``pipeline.py:216`` TODO ("thread schema-set version once
# ``forge/templates/_shared/`` adopts a manifest with a version") — keep
# this as the single source until that manifest lands.
SCHEMA_VERSION = 1


DEFAULT_SCHEMA_ROOT = (
    Path(__file__).resolve().parent.parent / "templates" / "_shared" / "canvas-components"
)


def _banner_lines_ts() -> list[str]:
    """Banner emitted at the top of generated TS files."""
    return [
        "// AUTOGENERATED — DO NOT EDIT.",
        "// Source: forge/templates/_shared/canvas-components/*.props.schema.json",
        f"// Schema version: {SCHEMA_VERSION}",
        "// Regenerate via `python -m forge.codegen.canvas_props`.",
        "",
    ]


def _banner_lines_dart() -> list[str]:
    """Banner emitted at the top of generated Dart files (same syntax as TS)."""
    return _banner_lines_ts()


def _banner_lines_pydantic() -> list[str]:
    """Banner emitted at the top of generated Pydantic files (module docstring)."""
    return [
        '"""AUTOGENERATED — DO NOT EDIT.',
        "",
        "Source: forge/templates/_shared/canvas-components/*.props.schema.json",
        f"Schema version: {SCHEMA_VERSION}",
        "Regenerate via ``python -m forge.codegen.canvas_props`` (forge repo) or",
        "by re-running the per-project codegen pipeline.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
    ]


def load_canvas_schemas(root: Path | None = None) -> list[Schema]:
    """Load every canvas props schema sorted by title.

    Reuses :func:`forge.codegen.ui_protocol.load_all` — the glob pattern
    matches both ``*.schema.json`` and ``*.props.schema.json``.
    """
    return load_all(root or DEFAULT_SCHEMA_ROOT)


def emit_typescript(schemas: list[Schema]) -> str:
    """Emit a TS module declaring every canvas-props schema."""
    lines: list[str] = _banner_lines_ts()
    for schema in schemas:
        lines.append(_ts_for_schema(schema))
        lines.append("")
    return "\n".join(lines)


def emit_dart(schemas: list[Schema]) -> str:
    """Emit a Dart library with sealed classes for every canvas-props schema.

    Each top-level class has:
        * ``final`` fields (camelCase, matching Dart conventions)
        * a named const constructor with required/optional positional flags
        * a ``fromJson`` factory + ``toJson`` map
        * nullability respected per JSON Schema ``required``

    Nested array-of-typed-object properties get a dedicated sealed inner
    class per nesting level, named ``<parent-without-Props><field-singular>``
    (e.g. ``DynamicFormProps.fields`` → ``List<DynamicFormField>``;
    ``WorkflowDiagramProps.nodes`` → ``List<WorkflowDiagramNode>``).
    Inner classes are emitted **before** the parent class in the file
    so Dart's top-down compilation resolves them without forward
    references.

    Schemas whose array items are typeless objects (``items: {type:
    object}`` with no ``properties``, e.g. ``DataTable.rows`` which sets
    ``additionalProperties: true``) keep ``List<Map<String, dynamic>>``
    — there is no fixed shape to type against.
    """
    lines: list[str] = _banner_lines_dart()
    for schema in schemas:
        lines.append(_dart_for_canvas_schema(schema))
        lines.append("")
    return "\n".join(lines)


# -- Dart helpers (canvas-only) -----------------------------------------------
#
# We do not reuse :func:`forge.codegen.ui_protocol._dart_for_schema` because
# the canvas surface needs typed nested classes. The ui-protocol emitter
# stays "flat" (``Map<String, dynamic>`` for nested object items) because
# AG-UI payloads use ``additionalProperties: true`` and there is no fixed
# shape to type against. Canvas component props are the opposite: each
# nested item has a small, closed schema and downstream consumers
# (``data_table.dart``, ``dynamic_form.dart``, ``workflow_diagram.dart``)
# expect typed access.


# Dart reserved words we must avoid using as a field identifier. Mapped
# values mirror what the hand-written Dart components already used (e.g.
# ``default`` → ``defaultValue``) so swapping the components over to the
# generated classes is a renaming refactor, not a behaviour change.
_DART_RESERVED_FIELD_REMAP: dict[str, str] = {
    "default": "defaultValue",
}


def _singularize(name: str) -> str:
    """Return a best-effort singular form of ``name`` for nested-class naming.

    Limited rules — only what the shipped canvas schemas need:

        * trailing ``ies`` → ``y`` (``categories`` → ``category``)
        * trailing ``s`` → ``""`` (``fields`` → ``field``, ``nodes`` → ``node``)

    Leaves the name as-is when no rule fits. Generated classes don't
    blow up — a non-stripped plural just produces a slightly odd class
    name (``Series`` from ``series``) which is still valid Dart.
    """
    if name.endswith("ies") and len(name) > 3:
        return name[:-3] + "y"
    if name.endswith("s") and len(name) > 1:
        return name[:-1]
    return name


def _pascal_case(name: str) -> str:
    """Convert a snake_case or camelCase identifier to PascalCase."""
    parts = name.replace("-", "_").split("_")
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def _nested_class_name(parent_title: str, field_name: str) -> str:
    """Synthesise the inner-class name for an array-of-object field.

    ``parent_title`` is the parent schema's PascalCase title (e.g.
    ``DynamicFormProps``); the trailing ``Props`` is stripped so the
    generated class names match the component domain vocabulary
    (``DynamicFormField`` reads better than ``DynamicFormPropsField``).
    """
    base = parent_title
    if base.endswith("Props"):
        base = base[: -len("Props")]
    return f"{base}{_pascal_case(_singularize(field_name))}"


def _is_typed_object_array(prop: dict[str, Any]) -> bool:
    """True if ``prop`` is ``{type: array, items: {type: object, properties: ...}}``."""
    if prop.get("type") != "array":
        return False
    items = prop.get("items")
    if not isinstance(items, dict):
        return False
    if items.get("type") != "object":
        return False
    return isinstance(items.get("properties"), dict) and bool(items.get("properties"))


def _dart_field_name(json_key: str) -> str:
    """Map a JSON key onto a Dart-safe field identifier."""
    camel = _to_camel_case(json_key)
    return _DART_RESERVED_FIELD_REMAP.get(camel, camel)


def _dart_type_for_canvas(prop: dict[str, Any], *, nested_class: str | None = None) -> str:
    """Return the Dart type expression for ``prop``.

    Mirrors :func:`forge.codegen.ui_protocol._dart_type_for` but, when
    ``prop`` is a typed-object array AND a ``nested_class`` name was
    threaded in by the parent walker, lifts the inner type to that
    sealed class instead of collapsing to ``Map<String, dynamic>``.
    Untyped (``items: {}``) or ``additionalProperties: true`` items
    still degrade to ``Map<String, dynamic>`` — there is no fixed
    shape to type against.
    """
    if "enum" in prop:
        return "String"
    if "const" in prop:
        return "String"
    ty = prop.get("type")
    if ty == "string":
        return "String"
    if ty == "integer":
        return "int"
    if ty == "number":
        return "double"
    if ty == "boolean":
        return "bool"
    if ty == "array":
        items = prop.get("items") or {"type": "string"}
        if nested_class and _is_typed_object_array(prop):
            return f"List<{nested_class}>"
        inner = _dart_type_for_canvas(items)
        return f"List<{inner}>"
    if ty == "object":
        return "Map<String, dynamic>"
    if ty is None:
        return "dynamic"
    raise GeneratorError(f"Unsupported JSON Schema type: {ty!r}")


def _dart_from_json_for_canvas(
    prop: dict[str, Any],
    json_key: str,
    required: bool,
    *,
    nested_class: str | None = None,
) -> str:
    """Dart expression that pulls the value for ``json_key`` out of ``json``."""
    raw = f"json['{json_key}']"
    if "enum" in prop or "const" in prop:
        cast = f"{raw} as String"
    else:
        ty = prop.get("type")
        if ty == "string":
            cast = f"{raw} as String"
        elif ty == "integer":
            cast = f"{raw} as int"
        elif ty == "number":
            cast = f"({raw} as num).toDouble()"
        elif ty == "boolean":
            cast = f"{raw} as bool"
        elif ty == "array":
            items = prop.get("items") or {"type": "string"}
            if nested_class and _is_typed_object_array(prop):
                cast = (
                    f"({raw} as List)"
                    ".whereType<Map>()"
                    f".map((e) => {nested_class}.fromJson(Map<String, dynamic>.from(e)))"
                    ".toList(growable: false)"
                )
            else:
                inner = _dart_type_for_canvas(items)
                if inner == "Map<String, dynamic>":
                    cast = f"({raw} as List).cast<Map<String, dynamic>>()"
                else:
                    cast = f"({raw} as List).cast<{inner}>()"
        elif ty == "object":
            cast = f"Map<String, dynamic>.from({raw} as Map)"
        else:
            cast = raw
    if required:
        return cast
    return f"{raw} == null ? null : ({cast})"


def _dart_to_json_for_canvas(
    prop: dict[str, Any],
    field_name: str,
    required: bool,
    *,
    nested_class: str | None = None,
) -> str:
    """Dart expression serialising ``field_name`` back to a JSON-shaped value."""
    if nested_class and _is_typed_object_array(prop):
        if required:
            return f"{field_name}.map((e) => e.toJson()).toList()"
        return f"{field_name}?.map((e) => e.toJson()).toList()"
    return field_name


def _dart_for_canvas_object(
    *,
    title: str,
    description: str,
    body: dict[str, Any],
) -> str:
    """Emit a Dart immutable class for one ``object`` schema body.

    Walks ``properties`` once and, for every typed-object array field,
    recurses to emit the nested class before the current one.
    """
    props = body.get("properties") or {}
    required = set(body.get("required") or [])

    inner_blocks: list[str] = []
    field_decls: list[str] = []
    ctor_params: list[str] = []
    from_json_parts: list[str] = []
    to_json_parts: list[str] = []

    for name in props:
        prop_schema = props[name]
        is_typed_array = _is_typed_object_array(prop_schema)
        nested_class: str | None = None
        if is_typed_array:
            nested_class = _nested_class_name(title, name)
            items = prop_schema["items"]
            inner_blocks.append(
                _dart_for_canvas_object(
                    title=nested_class,
                    description=str(items.get("description") or ""),
                    body=items,
                )
            )

        dart_type = _dart_type_for_canvas(prop_schema, nested_class=nested_class)
        is_required = name in required
        # ``dynamic`` is already nullable in Dart — adding ``?`` is a
        # compile error. Skip the marker for optional dynamic fields
        # (e.g. ``DynamicFormField.default`` whose schema is the
        # wildcard ``{}``).
        nullable_mark = "" if (is_required or dart_type == "dynamic") else "?"
        field_name = _dart_field_name(name)

        field_decls.append(f"  final {dart_type}{nullable_mark} {field_name};")
        ctor_params.append(f"    {'required ' if is_required else ''}this.{field_name},")
        from_json_parts.append(
            "      "
            f"{field_name}: "
            f"{_dart_from_json_for_canvas(prop_schema, name, is_required, nested_class=nested_class)},"
        )
        to_json_parts.append(
            "      "
            f"'{name}': "
            f"{_dart_to_json_for_canvas(prop_schema, field_name, is_required, nested_class=nested_class)},"
        )

    if body.get("additionalProperties") is True:
        field_decls.append("  final Map<String, dynamic> extras;")
        ctor_params.append("    this.extras = const {},")

    lines: list[str] = []
    if inner_blocks:
        # ``inner_blocks`` is already a list of complete class bodies —
        # separate them with a blank line so the rendered file stays
        # readable (each class header sits on its own line, not glued
        # to the previous class's closing brace).
        for block in inner_blocks:
            lines.append(block)
            lines.append("")
    if description:
        lines.append(f"/// {description}")
    lines.append(f"class {title} {{")
    lines.extend(field_decls)
    lines.append("")
    lines.append(f"  const {title}({{")
    lines.extend(ctor_params)
    lines.append("  });")
    lines.append("")
    lines.append(f"  factory {title}.fromJson(Map<String, dynamic> json) => {title}(")
    lines.extend(from_json_parts)
    lines.append("  );")
    lines.append("")
    lines.append("  Map<String, dynamic> toJson() => {")
    lines.extend(to_json_parts)
    lines.append("  };")
    lines.append("}")
    return "\n".join(lines)


def _dart_for_canvas_schema(schema: Schema) -> str:
    """Emit Dart classes for a top-level canvas-props schema."""
    body = schema.body
    if body.get("type") != "object":
        raise GeneratorError(f"{schema.title}: top-level schema must be type=object")
    return _dart_for_canvas_object(
        title=schema.title,
        description=schema.description,
        body=body,
    )


def emit_pydantic(schemas: list[Schema]) -> str:
    """Emit Pydantic v2 ``BaseModel`` classes for every canvas-props schema.

    The body uses the per-schema renderer from
    :mod:`forge.codegen.ui_protocol` — the only difference vs.
    ``forge.codegen.ui_protocol.emit_pydantic`` is the banner, which
    points at the canvas-components schema directory and ships
    ``schema_version`` so downstream provenance can tell which schema
    set drove the file.
    """
    lines: list[str] = _banner_lines_pydantic()
    for schema in schemas:
        lines.append(_pydantic_for_schema(schema))
        lines.append("")
    return "\n".join(lines)


# -- Repo-side regeneration ---------------------------------------------------
#
# Used by ``python -m forge.codegen.canvas_props`` to regenerate the
# checked-in files under ``packages/``. Per-project codegen (which
# emits Pydantic into the generated backend) lands in a later commit.


def _repo_root() -> Path:
    """Return the forge repo root, located three levels above this file.

    ``forge/codegen/canvas_props.py`` → repo root is ``../../`` above it.
    """
    return Path(__file__).resolve().parent.parent.parent


# Map of (target-language, output-path-relative-to-repo-root). Adding a
# fourth package means adding a row here.
_PACKAGE_TARGETS: tuple[tuple[str, str], ...] = (
    ("typescript", "packages/canvas-vue/src/generated/props.ts"),
    ("typescript", "packages/canvas-svelte/src/generated/props.ts"),
    ("dart", "packages/forge-canvas-dart/lib/src/generated/props.dart"),
)


def regenerate_packages(repo_root: Path | None = None) -> list[Path]:
    """Regenerate canvas-props files under ``packages/`` in the forge repo.

    Returns the list of paths written, sorted. Idempotent: writes are
    byte-identical on repeated invocations.
    """
    root = repo_root or _repo_root()
    schemas = load_canvas_schemas()
    bodies = {
        "typescript": emit_typescript(schemas),
        "dart": emit_dart(schemas),
    }
    written: list[Path] = []
    for lang, rel in _PACKAGE_TARGETS:
        target = root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(bodies[lang], encoding="utf-8")
        written.append(target)
    return sorted(written)


def main() -> int:
    """CLI entry point: regenerate every canvas-props target in the repo."""
    written = regenerate_packages()
    for p in written:
        print(f"wrote {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
