"""Generate TypeScript / Dart types for **canvas component props**.

The canonical schemas live in
``forge/templates/_shared/canvas-components/*.props.schema.json``. Today
this module emits TypeScript and Dart; Pydantic lands in a follow-on
commit of the same theme.

Targets:

    * ``packages/canvas-vue/src/generated/props.ts``
    * ``packages/canvas-svelte/src/generated/props.ts``
    * ``packages/forge-canvas-dart/lib/src/generated/props.dart``

The schema → type mapping lives in :mod:`forge.codegen.ui_protocol`;
this module rebrands the banner so the generated file points at the
canvas-component schema directory and ships the right
``schema_version`` tag.

Run as a script to regenerate the files inside the forge repo
(``python -m forge.codegen.canvas_props``).
"""

from __future__ import annotations

from pathlib import Path

from forge.codegen.ui_protocol import (
    Schema,
    _dart_for_schema,
    _ts_for_schema,
    load_all,
)

# Bump when the canvas schema-set grows a breaking change. Mirrors the
# ``pipeline.py:216`` TODO ("thread schema-set version once
# ``forge/templates/_shared/`` adopts a manifest with a version") — keep
# this as the single source until that manifest lands.
SCHEMA_VERSION = 1


DEFAULT_SCHEMA_ROOT = (
    Path(__file__).resolve().parent.parent / "templates" / "_shared" / "canvas-components"
)


def _banner_lines_ts() -> list[str]:
    """Banner emitted at the top of generated TS files."""
    return [
        "// AUTOGENERATED — DO NOT EDIT.",
        "// Source: forge/templates/_shared/canvas-components/*.props.schema.json",
        f"// Schema version: {SCHEMA_VERSION}",
        "// Regenerate via `python -m forge.codegen.canvas_props`.",
        "",
    ]


def _banner_lines_dart() -> list[str]:
    """Banner emitted at the top of generated Dart files (same syntax as TS)."""
    return _banner_lines_ts()


def load_canvas_schemas(root: Path | None = None) -> list[Schema]:
    """Load every canvas props schema sorted by title.

    Reuses :func:`forge.codegen.ui_protocol.load_all` — the glob pattern
    matches both ``*.schema.json`` and ``*.props.schema.json``.
    """
    return load_all(root or DEFAULT_SCHEMA_ROOT)


def emit_typescript(schemas: list[Schema]) -> str:
    """Emit a TS module declaring every canvas-props schema."""
    lines: list[str] = _banner_lines_ts()
    for schema in schemas:
        lines.append(_ts_for_schema(schema))
        lines.append("")
    return "\n".join(lines)


def emit_dart(schemas: list[Schema]) -> str:
    """Emit a Dart library with immutable classes for every canvas-props schema.

    Each class has:
        * ``final`` fields (camelCase, matching Dart conventions)
        * a named const constructor with required/optional positional flags
        * a ``fromJson`` factory + ``toJson`` map
        * nullability respected per JSON Schema ``required``

    Nested array-item objects collapse to ``List<Map<String, dynamic>>``
    — matching the existing ``ui_protocol.py`` Dart emitter's strategy
    (no recursive nested-class generation today).
    """
    lines: list[str] = _banner_lines_dart()
    for schema in schemas:
        lines.append(_dart_for_schema(schema))
        lines.append("")
    return "\n".join(lines)


# -- Repo-side regeneration ---------------------------------------------------
#
# Used by ``python -m forge.codegen.canvas_props`` to regenerate the
# checked-in files under ``packages/``. Per-project codegen (which
# emits Pydantic into the generated backend) lands in a later commit.


def _repo_root() -> Path:
    """Return the forge repo root, located three levels above this file.

    ``forge/codegen/canvas_props.py`` → repo root is ``../../`` above it.
    """
    return Path(__file__).resolve().parent.parent.parent


# Map of (target-language, output-path-relative-to-repo-root). Adding a
# fourth package means adding a row here.
_PACKAGE_TARGETS: tuple[tuple[str, str], ...] = (
    ("typescript", "packages/canvas-vue/src/generated/props.ts"),
    ("typescript", "packages/canvas-svelte/src/generated/props.ts"),
    ("dart", "packages/forge-canvas-dart/lib/src/generated/props.dart"),
)


def regenerate_packages(repo_root: Path | None = None) -> list[Path]:
    """Regenerate canvas-props files under ``packages/`` in the forge repo.

    Returns the list of paths written, sorted. Idempotent: writes are
    byte-identical on repeated invocations.
    """
    root = repo_root or _repo_root()
    schemas = load_canvas_schemas()
    bodies = {
        "typescript": emit_typescript(schemas),
        "dart": emit_dart(schemas),
    }
    written: list[Path] = []
    for lang, rel in _PACKAGE_TARGETS:
        target = root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(bodies[lang], encoding="utf-8")
        written.append(target)
    return sorted(written)


def main() -> int:
    """CLI entry point: regenerate every canvas-props target in the repo."""
    written = regenerate_packages()
    for p in written:
        print(f"wrote {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
