<script setup lang="ts">
// Layer-1 pure-UI component generated by Forge (component_StatusDot).
// A small colored status indicator dot. Variants map to explicit Tailwind
// color classes (not theme tokens) so the semantic meaning is stable across
// generated themes. An optional `pulse` adds a ping animation, and a default
// slot renders an inline label beside the dot.
import { type HTMLAttributes, computed } from 'vue'
import { cn } from '@/shared/lib/utils'

type Variant = 'success' | 'warning' | 'danger' | 'neutral' | 'info'
type Size = 'sm' | 'md' | 'lg'

const props = withDefaults(
  defineProps<{
    variant?: Variant
    size?: Size
    pulse?: boolean
    class?: HTMLAttributes['class']
  }>(),
  {
    variant: 'neutral',
    size: 'md',
    pulse: false,
    class: undefined,
  },
)

const colorClass = computed(
  () =>
    ({
      success: 'bg-emerald-500',
      warning: 'bg-amber-500',
      danger: 'bg-red-500',
      neutral: 'bg-gray-400',
      info: 'bg-sky-500',
    })[props.variant],
)

const sizeClass = computed(
  () =>
    ({
      sm: 'h-1.5 w-1.5',
      md: 'h-2.5 w-2.5',
      lg: 'h-3.5 w-3.5',
    })[props.size],
)
</script>

<template>
  <span :class="cn('inline-flex items-center gap-2', props.class)">
    <span class="relative inline-flex shrink-0">
      <span
        v-if="pulse"
        :class="
          cn(
            'absolute inline-flex h-full w-full animate-ping rounded-full opacity-75',
            colorClass,
          )
        "
        aria-hidden="true"
      />
      <span
        :class="cn('relative inline-flex rounded-full', sizeClass, colorClass)"
      />
    </span>
    <span v-if="$slots.default" class="text-sm text-muted-foreground">
      <slot />
    </span>
  </span>
</template>
