<script setup lang="ts">
// Layer-1 pure-UI component generated by Forge (component_PageActionGroup).
// A responsive toolbar for page-level actions. `primary` actions render as
// inline buttons; `overflow` actions are tucked into a "..." dropdown menu.
// Built on the base-template `button` and `dropdown-menu` primitives.
import { type HTMLAttributes, type FunctionalComponent, computed } from 'vue'
import type { VariantProps } from 'class-variance-authority'
import { MoreHorizontal } from 'lucide-vue-next'
import { cn } from '@/shared/lib/utils'
import { Button, buttonVariants } from '@/shared/ui/button'
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
} from '@/shared/ui/dropdown-menu'

type ButtonVariant = VariantProps<typeof buttonVariants>['variant']

export interface PageAction {
  /** Stable key + accessible label for the action. */
  label: string
  /** Invoked when the action is triggered. */
  onSelect?: () => void
  /** Button variant (primary actions only); ignored in the overflow menu. */
  variant?: ButtonVariant
  /** Optional leading icon (e.g. a `lucide-vue-next` component). */
  icon?: FunctionalComponent
  disabled?: boolean
}

const props = withDefaults(
  defineProps<{
    /** Actions rendered inline as buttons. */
    primary?: PageAction[]
    /** Actions tucked behind the overflow ("...") menu. */
    overflow?: PageAction[]
    class?: HTMLAttributes['class']
  }>(),
  {
    primary: () => [],
    overflow: () => [],
    class: undefined,
  },
)

const hasOverflow = computed(() => props.overflow.length > 0)
</script>

<template>
  <div
    :class="
      cn('flex flex-wrap items-center justify-end gap-2', props.class)
    "
  >
    <!-- Lead slot for free-form content (e.g. a title or filter chips). -->
    <slot name="lead" />

    <Button
      v-for="action in primary"
      :key="action.label"
      :variant="action.variant ?? 'default'"
      :disabled="action.disabled"
      @click="action.onSelect?.()"
    >
      <component :is="action.icon" v-if="action.icon" class="h-4 w-4" />
      <span>{{ action.label }}</span>
    </Button>

    <!-- Extra free-form actions slot, always inline. -->
    <slot />

    <DropdownMenu v-if="hasOverflow">
      <DropdownMenuTrigger as-child>
        <Button variant="outline" size="icon" aria-label="More actions">
          <MoreHorizontal class="h-4 w-4" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem
          v-for="action in overflow"
          :key="action.label"
          :disabled="action.disabled"
          @select="action.onSelect?.()"
        >
          <component :is="action.icon" v-if="action.icon" class="h-4 w-4" />
          <span>{{ action.label }}</span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  </div>
</template>
