export { useAgentClient } from './composables/useAgentClient'
export { useAiChat } from './composables/useAiChat'
export type { ChatMessage } from './composables/useAiChat'
export { useWorkspace } from './composables/useWorkspace'
export { useCanvas } from './composables/useCanvas'
export type { AgentState, DeepAgentCustomPayload, WorkspaceActivity, WorkspaceAction, ToolCallInfo } from './types'
export { default as AiChat } from './ui/AiChat.vue'
export { default as AiChatButton } from './ui/AiChatButton.vue'
export { default as AiChatMessage } from './ui/AiChatMessage.vue'
export { default as AgentStatusBar } from './ui/AgentStatusBar.vue'
export { default as WorkspacePane } from './workspace/WorkspacePane.vue'
export { default as CanvasPane } from './canvas/CanvasPane.vue'
